### ISSUE TITLE
Camera plugin not working in ionic View app

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud#1]
Hey guys!  I'm loving ionic-cloud thus far, but one issue that I ran into today was that the Camera plugin doesn't seem to work inside of the IonicView app. Though I feel like I may be doing something wrong...

```
Camera.getPicture(options).then((img) => { // do cool stuff }, 
(err) => { console.log('There was an error: ' + JSON.stringify(err)); });

```

Whenever I'm in the IonicView app the error handler gets executed and all I see is:  "There was an error: {}"

If I generate an actual apk and install that on my phone it works like a charm. Am I missing something? I'm using **ionic2 Beta8** and the latest version of the ionicView app.

Thanks so much for your time!

**Comment by dwieeb** [comment]
Hiya! This issue doesn't seem to relate to the Ionic Cloud client. There's likely an issue with the Cordova plugin or Ionic View. Can you report your issue over at the [Ionic View issues](https://github.com/driftyco/ionic-view-issues/issues) with steps to reproduce the error?
