### ISSUE TITLE
User Authorization header not sent on refresh

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#10]
I am currently developing in the browser.
After login-in everything works fine and I am able to save user data. 
```
this.user.set('firstName', this.settings.firstName);
this.user.save()
```
But after I refresh the browser it fails - I get a 401. it seems like the **Authorization header** isn't being sent. I do see the token exists in the local storage.
Should I be taking some sort of action when the app starts?

**Comment by dwieeb** [comment]
@sagivf I think your problem might be that you're not passing `{'remember': true}` to the login method. I am just about ready to release a new version that defaults this to be true.

**Comment by sagivf** [comment]
@dwieeb I am passing it, i'll check again after you release.

**Comment by dwieeb** [comment]
Oh, right, because you said you saw it in local storage. 

Hmm, I'm not sure. I've never seen this behavior. You shouldn't need to do anything when the app starts. Once a user logs in, their token is stored indefinitely and it should be picked up by our client client if it exists.

Yeah, let's check with the new version when it comes out.

**Comment by dwieeb** [comment]
@sagivf New version is out. There were some changes since the last release, you can see them in [this diff](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide/_compare/871ca81e58518259a65f650651fe3326b182e040...2fa37d45d51d656d19a95a41cd82a13b4e89fa4e).

If you're still getting this error, I'm really not sure what the problem would be. Internally, the HTTP client takes a `TokenContext` (instead of a token). This means it now tries to get the token from the context (in this case, localstorage) every time it makes a request.

Let me know how it works!

**Comment by cklanac** [comment]
@sagivf I did a basic implementation on v0.0.12 and got the same error. FWIW, I couldn't implement the static methods on v0.0.14.

Here's the whole process
**Initial signup, just for reference...**
```
ngOnInit() {
    var authProvider = 'basic';
    var authSettings = { 'remember': true };
    var authDetails = {'name': 'fullname', 'email': 'hello@ionic.io', 'password': 'puppies123'};
    Auth.signup(authDetails).then(() => {
      console.log("`user` is now registered");
    }, (err) => {
      console.log("something went wrong!")
    });
}
```

**Subsequent Login and Save works fine...**
Confirmed the Custom Data in the Ionic Platform dashboard
```
ngOnInit() {
    var authProvider = 'basic';
    var authSettings = { 'remember': true };
    var authDetails = {'name': 'fullname', 'email': 'hello@ionic.io', 'password': 'puppies123'};
    Auth.login(authProvider, authSettings, authDetails).then(() => {
      console.log("`user` is now the authenticated user");
        this.currentUser = User.current(); 
        this.currentUser.set('foo', "bar");
        this.currentUser.save()
    }, (err) => {
      console.log("something went wrong!")
    });
}
```

**Update custom data without re-logging in.**

```
ngOnInit() {
    var authProvider = 'basic';
    var authSettings = { 'remember': true };
    var authDetails = {'name': 'fullname', 'email': 'hello@ionic.io', 'password': 'puppies123'};
    this.currentUser = User.current(); // Works!
    console.log(this.currentUser); // <<== this returns a valid user with _id
    // And valid tokens are in Resources
    this.currentUser.set('foo', "baz");
    this.currentUser.save(); // <<== Throws error
}
```
**Console Errors**
```
PATCH https://api.ionic.io/auth/users/e4b3b822-2507-4c03-9214-af2621b361a0 401 (UNAUTHORIZED)
Ionic User: Error: UNAUTHORIZED(…)
EXCEPTION: Error: Uncaught (in promise): Error: UNAUTHORIZED
Unhandled Promise rejection: UNAUTHORIZED ; Zone: angular ; Task: XMLHttpRequest.addEventListener:readystatechange ; Value: Error: UNAUTHORIZED(…)
```

**Comment by sagivf** [comment]
Thanks @cklanac. Looks like you are have the same issue as me. @dwieeb looks like this is not really operational as it requires logging in every time. 

Even that wouldn't be possible as the password is not available for the developer(rightfully so).

**Comment by dwieeb** [comment]
@sagivf @cklanac We obviously don't want the developer to login the user every time. Please see my comments: https://github.com/driftyco/ionic-cloud-angular/issues/6#issuecomment-230167536 and try the latest 0.0.14. I just tried your example with 0.0.14 and was able to update my user.

**Comment by sagivf** [comment]
It's working nicely after upgrading to 0.0.14 but there is a small thing which i'm not sure are a problem.
For the user full details to be loaded (custom data) I have do do the following:

```
const isAuthenticated = this.auth.isAuthenticated();
if (isAuthenticated) {
  this.user.load();
}
```

**Comment by sagivf** [comment]
@dwieeb shall I open an issue for this?

**Comment by dwieeb** [comment]
@sagivf Looks like a bug. I published a new version. Thanks! If there are additional issues, please feel free to open new ones.
