### ISSUE TITLE
IOS App stops working

### ISSUE THREAD

**Issue by zapbuild** [driftyco/ionic-cloud#101]
Hi 
My IOS mobile app for iPad has stopped working. It was working fine before but since when the IOS certificates(for push notifications) expired, it stopped working. Though, I renewed IOS certificates and apple stated that now everything should be working fine. The app is using ionic push notifications. Please let me know how you could help me in this.

I noticed that there are some changes in the ionic api and version 2 has been released. Please see the link: https://apps.ionic.io/api/v1/app/5b6e463d/users/identify

Please guide me know how to fix it.

Thanks
Jatinder Singh

**Comment by ericb** [comment]
You need to follow the [migration guide](http://docs.ionic.io/migration.html) to update your app from the old alpha services which have been deprecated for quite some time now.
