### ISSUE TITLE
Ionic Push - Icon notification different than icon app / Plugin configuration

### ISSUE THREAD

**Issue by Lestt** [driftyco/ionic-cloud#103]
Hi all,

I would like to know if it's possible to have an app icon different than the notification icon.
I followed this [link](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#additional-resources), created a hook which copy my file(_notif.png_) into the android platform folder.
Everything will be copied into the **res/mipmap-*** folders. In these folders, there are my app icon too.
I would like to know if it's possible to have an icon for the notification (i.e _notif.png_) and an icon for my app (_icon.png_) in these folders.
In my app, i tried to configure the **phonegap-plugin-push** plugin through the **ionicCloudProvider** like this:

```
.config(function($ionicCloudProvider) {
  $ionicCloudProvider.init({
    "core": {
      "app_id": "XXXXX"
    },
    "push": {
      "sender_id": "YYYYYY",
      "pluginConfig": {
        "android": {
          "icon": "notif",
          "iconColor": "blue"
        }
      }
    }
  });
})
```
The color is blue, but the icon is still a blank square.
Should i have to configure the **phonegap-plugin-push** independently with **PushNotification.init()** method ?

**Comment by Lestt** [comment]
Well it seems it is a **phonegap-plugin-push** issue according to this [post](https://github.com/phonegap/phonegap-plugin-push/issues/1314). The plugin doesn't use the mipmap folders with **cordova-android@6.0.0**, so i have to downgrade to **cordova-android@5.2.2** and it's ok.

**Comment by ericb** [comment]
Thanks for the update @Lestt -- I'm closing this out but linking to phonegap/phonegap-plugin-push#1314 for future reference. 👍
