### ISSUE TITLE
Document snapshot update metadata

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic-cloud#104]
In the absence of a fix for driftyco/ionic-cli#660 I was ready to use the RESTful api, to implement this. There is no documented way to do this (http://docs.ionic.io/api/endpoints/deploy.html#patch-snapshots-snapshot_id), but from looking at the web interface it appears it can be done like the following.

```
"user_metadata": {
    "key1":"123456",
    "key2":"value2"
}
```

note that I have not verified that I am allowed to use this option through the api.

**Comment by ericb** [comment]
This was intended to be documented but we had a typo on our end that prevented the field lookup. I fixed that up so it's now showing correctly. Thanks @AgDude!
