### ISSUE TITLE
Build keeps failing 

### ISSUE THREAD

**Issue by istMagic** [driftyco/ionic-cloud#107]
Hi ,

When I want to build an app in Ionic Cloud, I keep getting a build that is failed.
The output that I get  is "Error: Unpublished by drifty" with a date that is more then a year.
I tried creating a new app and with a different platform and still getting the same error.

Thanks!

**Comment by dwieeb** [comment]
You likely are using the old `com.ionic.keyboard` plugin in your app. Please update it to the latest version of `ionic-plugin-keyboard` (https://github.com/driftyco/ionic-plugin-keyboard) and delete any references in `package.json` to the old plugin.
