### ISSUE TITLE
Ionic Serve Fails After Adding Ionic Cloud Angular

### ISSUE THREAD

**Issue by amymarsh4work** [driftyco/ionic-cloud#108]
Hi,
I'm having problems getting the cloud client installed and the project to serve properly. I'm getting an error in the Chrome console that states: "Uncaught TypeError: angular.element is not a function(...)" and a white screen.

This is a problem when running 'ionic serve'. Running 'ionic emulate ios' works. It's really inconvenient because it's so fast to do much of the development in the browser.

To eliminate my existing project quirks, I decided to reproduce it on a fresh project. I then verified that ionic serve was working. After that, I followed the Cloud Module installation steps here: http://docs.ionic.io/setup.html

This is what my app.module.ts file looks like:
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';

import { CloudSettings, CloudModule } from '@ionic/cloud-angular';

const cloudSettings: CloudSettings = {
  'core': {
    'app_id': 'f18445ea'
  }
};

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    CloudModule.forRoot(cloudSettings)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}

If I go back into my app.module.ts and comment out the CloudModule.forRoot(cloudSettings) line in the imports, it will serve again properly. I also noticed that the main.js file in www/build is larger when CloudModule is present (which makes sense). However, on my existing project it's much smaller which is strange. This is leading me to believe that there's something going on with the build process. I also tried deleting my node_modules directory and doing an npm install. I still have the same problem. :(

Still, if I can at least get this working on a blank starter project with your help, it could clue me in as to what is going on with my other project.

Here is my ionic info:
Cordova CLI: 6.1.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 7.3 Build version 7D175

Your help is very much appreciated,
Amy

**Comment by amymarsh4work** [comment]
FYI: I just tried deleting my node_modules directory and doing an npm install. I still have the same problem. :(

**Comment by amymarsh4work** [comment]
Update: Did an install on a different machine and the starter site serve worked with the Cloud module installed and configured. It must be something with my environment. The only thing I can think of that's a recent change is that I installed Typings globally for Leaflet. 

If you have no suggestions that come to mind, this issue can be closed.

**Comment by dwieeb** [comment]
The only way I could think of this happening is if `angular` is defined on `window` but it is not angular 1.

I realize this is an Angular 2 project, but somehow it got past this if statement: https://github.com/driftyco/ionic-cloud/blob/master/src/angular.ts#L11-L13

**Comment by amymarsh4work** [comment]
Update: I found that disabling the AngularJS Batarang extension in Chrome resolved this problem!
