### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#11]
Couldn't get it to work at all in the browser.
In the ios emulator and my device after some debugging I have found that there seems to be an issue here -
https://github.com/driftyco/ionic-cloud/blob/master/src/auth.ts#L156
seems like using `this.client.post` instead of `this.client.request('POST')` opens the facebook page. 

**but** event after hacking at it I get this when it opens -

![image](https://cloud.githubusercontent.com/assets/1857466/16443561/44d4da04-3de2-11e6-8f07-684af7fe83a0.png)

Is this feature functional?

**Comment by dwieeb** [comment]
@sagivf Social and custom authentication require the [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) plugin to function, currently. We'd like to investigate alternatives to this. For now, I haven't had a chance to look into this (been busy writing docs!), but last time I checked, all types of authentication in the cloud client are functional.

**Comment by sagivf** [comment]
@devnetics I have the InAppBrowser installed. When you can try it out, I hacked at it and it defiantly seems broken. If your positive it works i'll try out again from scratch.

**Comment by dwieeb** [comment]
@sagivf Right, sorry, I didn't mean to imply you didn't have it installed (otherwise you wouldn't even see the facebook page). I more so meant it's a required Cordova plugin, so you need to test on a device or an emulator to test social authentication.

I'm not positive it works. I'll try this tomorrow and confirm.

The error you're getting [seems to be common](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=facebook%20android%20you%20are%20not%20logged%20in) across tools using Facebook auth.

**Comment by sagivf** [comment]
Thanks @dwieeb, I tried on the emulator and the device. 
I'll check out https://github.com/driftyco/ionic-cloud/issues/10 but I think the first step is https://github.com/driftyco/ionic-cloud/blob/master/src/auth.ts#L156 seems like something there is faulty.

**Comment by dwieeb** [comment]
There was an issue on that line, like you said. I just pushed a fix. 

As for the other issue, from the look of it, Facebook just made this a hell of a lot more difficult for us to use their authentication. I was unable to get past the `Not Logged in. You are not logged in. Please log in and try again.` error as well. See http://stackoverflow.com/questions/31879804/you-are-not-logged-in-please-log-in-and-try-again.

From the look of it, Facebook just changed their dashboard and authentication scheme out of the blue and broke a bunch of stuff for people. This is pretty normal for Facebook.

I guess I'll have to look at this later, but it looks like it could be solved with the right app settings in Facebook. May need to add an Android platform in Facebook settings with bundle ID, activity name, and key hashes.

**Comment by sagivf** [comment]
Thanks @dwieeb I to will try to investigate later this week, maybe I will have luck...

**Comment by devnetics** [comment]
@sagivf Have you done anything further with this?

**Comment by sagivf** [comment]
Sorry @devnetics - wasn't able to get to it yet.

**Comment by devnetics** [comment]
No worries @sagivf. I'm looking into this at the moment. I'll post here with any updates.

**Comment by sagivf** [comment]
@devnetics @dwieeb - hope i'm not stepping any bounds, but shouldn't this be in the beta release milestone? https://github.com/driftyco/ionic-cloud/milestone/1

**Comment by devnetics** [comment]
@sagivf Will you test something for me and see if this fixes the issue for you:

1) Go to your facebook developer account and navigate to the relevant app
2) Click "Add Product" on the left side menu
3) Select "Facebook Login"
4) Make sure it looks like this:

<img width="631" alt="screen shot 2016-07-15 at 10 17 44 am" src="https://cloud.githubusercontent.com/assets/6577282/16877297/693fc922-4a75-11e6-8665-e50843032a8b.png">

**Comment by sagivf** [comment]
@devnetics it works! Thanks for helping out.

There is how ever one issue, not critiacal at - 
After login out and in - you have re login to Facebook every time.

When I used http://ionicframework.com/docs/v2/native/facebook/ in a different app, it remembered the user credentials when login into facebook, and the user doesn't have to go trough the login again (lots of users doesn't remember their credentials).

Not sure this can be achieved in the current constellation, maybe through some sort of api integration with the app developer.

This is defiantly not a show stopper and I can now use this which is great! :)

Let me know if you want me open a task for this.

**Comment by devnetics** [comment]
No problem!

Yeah I noticed that as well on my end, I'm guessing it's related to their changes but I'll have to take a look next week. Go ahead and open a new issue for that, closing this one.
