### ISSUE TITLE
Apple rejecting update feature

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#111]
Don't know if this is a change in there policy or i'm miss presenting/using the feature, but apple has done it again - making life hard for developers and users. 

Any advice?

![image](https://cloud.githubusercontent.com/assets/1857466/21002524/fc15ae7a-bd2e-11e6-89cd-dbe776294609.png)

**Comment by ericb** [comment]
Hey @sagivf I've heard of this in one other instance. I'm not sure if this is something randomly decided during review, or if it's a bot looking for a button with the phrase 'Update App' or something along those lines, etc.

In the previous case our suggestion was to change how the updates are checked and (maybe behind the scenes) and then prompt the user letting them know an update is available (or just syncing in the background).

I never got confirmation if the suggestion worked or not, but I assume they were able to move forward.

**Comment by sagivf** [comment]
Thanks @ericb yee, thats what I think I'll do. 
I was going to make the update an in app pop up anyway.

I just don't get this company(apple), nowadays - government had less stupidity and bureaucracy then them...

**Comment by ericb** [comment]
Let us know how it goes, especially if they still reject it, but my assumption is that it will go through just fine.
