### ISSUE TITLE
Unable to Distribute iOS app (.ipa) with Ionic-Deeplinks App plugin & Universal Links.

### ISSUE THREAD

**Issue by uncle-mo** [driftyco/ionic-cloud#112]
Using "ionic package build ios ..." the build is successful but trying to distribute the app by using "Application Loader". The error is as follows:

> ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.associated-domains' in 'Payload/MyApp.app/MyApp' is not supported."

When I build the app locally it works. It should be noted that for the local build I've manually edited the application in xcode to enable and configure the "Associated Domains" since the ionic-deep-links app doesn't seem to do this automatically. (Looking at the source they added support then reverted back?). I suspect this is the issue and and if so is there is a workaround?

thanks.

**Comment by dwieeb** [comment]
Looks like we're waiting on this PR being remerged: https://github.com/driftyco/ionic-plugin-deeplinks/pull/21
