### ISSUE TITLE
Ionic package not working on V2

### ISSUE THREAD

**Issue by Mokto** [driftyco/ionic-cloud#118]
#### Short description of the problem:
Ionic package build android (or ios) not working.

#### What behavior are you expecting?
Compiles my files to prod into www and package my app on ionic.io.

**Steps to reproduce:**
1. ionic start test --v2 && cd test && ionic io init
2. ionic package build android

**Post the output of `ionic info` below please**

Your system information:

```
Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 It works with v1 applications but not with v2.

Thanks

**Comment by Mokto** [comment]
I forgot to show the stacktrace :

```
Upload errors occurred - Error: ENOENT: no such file or directory, open '/home/theo/Documents/cogeco-front/www/index.html'

Unexpected response format: undefined (CLI v2.1.17)
```

Thanks !

**Comment by pvdyck** [comment]
Your /www is probably empty. Ionic package zips the content of your www to package your app.
So you have to generate the www content locally. There are a number of ways to do it, but you already know that :-)

**Comment by Mokto** [comment]
It is empty. Shouldn't `ionic package build` build our javascript files depending on the platform ? I think It did on ionic v1.

I can do `ionic run browser` but native cordova plugins won't work, right ? How can I build an iOS app from within my Linux computer ?

Thanks.

**Comment by pvdyck** [comment]
"ionic build" or "npm run ionic:build" will build/package your app in the www directory, you then run the ionic package command.

**Comment by Mokto** [comment]
Thanks I'll try when i come back from vacations.

**Comment by ericb** [comment]
@Mokto What @pvdyck mentioned is correct, so I'm closing this for now. Let us know if you run into other issues.
