### ISSUE TITLE
Not detecting Cordova using Ionic Deploy

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cloud#12]
_From @Manduro on June 28, 2016 23:19_

Ionic Deploy requires `cordova.js` to be removed from `index.html`, as it gets added with the right path on start. This has always worked fine until recently.

Now, Ionic does not detect the app as being run in cordova anymore. Instead it is tagged as the `mobileweb` platform. This causes calls to cordova plugins to often fail, as the `platform.ready()` is launched on `domready` instead of `deviceready`.

When I re-add `cordova.js` to `index.html`, all is fine again.

It seems to be happening since `ionic-angular@2.0.0-beta.10`. It could also be an issue with https://github.com/driftyco/ionic-cloud

**Ionic Version**: 2.x

**Platform**: iOS (Android untested)

**Run `ionic info` from terminal/cmd prompt:**
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3 Build version 7D175 
```

_Copied from original issue: driftyco/ionic#7108_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue with the Ionic platform and not the framework i will be moving this issue to the appropriate repo. Thanks for using Ionic!

**Comment by jgw96** [comment]
Sorry did not mean to move this here.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cloud-issues#130

**Comment by dwieeb** [comment]
@Manduro says in https://github.com/driftyco/ionic-cloud-issues/issues/130#issuecomment-229394506

> @dwieeb I'm using the latest experimental cloud npm releases: `ionic-cloud-angular@0.0.12`. Could you see if you can reproduce this as well? All was fine with `ionic-angular@2.0.0-beta.9` by the way.
> 
> @jgw96 When does an issue belong here instead of in the code repo's for `ionic-cloud` and `ionic-cloud-angular`? I think this is an issue with the cloud lib, not with Ionic Cloud in general.

**Comment by dwieeb** [comment]
I will see if I can reproduce this issue. Just had a chat with @adamdbradley about the potential problems with our current approach in Ionic Deploy and Ionic 2. 

@jgw96 @Manduro: The CONTRIBUTING.md files in each repo explain the difference. https://github.com/driftyco/ionic-cloud-angular/blob/master/CONTRIBUTING.md#issues It's just going to be messy and I expect to be moving a lot of issues.

**Comment by dwieeb** [comment]
See also https://github.com/driftyco/ionic-platform-web-client/issues/17

**Comment by sagivf** [comment]
@dwieeb I seem to having a Ionic deploy and i'm guessing it's related.
When I use a deploy all the native stuff stops working ("Push" and "app version" plugin". I works like it does in the "Ionic View". 
The headers seem to overlap with the phones battary indicator witch also happens in the "Ionic View" - see the attachment: (It's white so a little hard to see)

![image](https://cloud.githubusercontent.com/assets/1857466/16609383/77492966-435c-11e6-826b-39d1421a472d.png)

**Comment by dwieeb** [comment]
@sagivf Did you remember to comment out the `cordova.js` include in your `index.html`? That's still required even for v2 apps. We are addressing this soon. 

@Manduro Can you try again with the latest version? Deploy is working without errors for me.

**Comment by sagivf** [comment]
Thanks @dwieeb it works and it's awesome!

The problem with the header still happens tough... I will open a  separate issue on it.

Why Does the cordova.js need to be removed? is it because once you use Ionic deploy it has to load it, or is it relevant to any Ionic project? Couldn't find anything about it in the docs.

**Comment by dwieeb** [comment]
@sagivf It doesn't use a different version or anything. When a new version is deployed to a device, it creates a subfolder with all your `www` assets. It then references that folder, but `<script src="cordova.js"></script>` is just wrong. So right now the _cloud client_, not the plugin, fixes that path. Ideally, that logic would be in the plugin so people wouldn't have to comment it out, but the way we're currently doing it works for now. So much stuff to do!

**Comment by dwieeb** [comment]
I believe the fix coming with https://github.com/driftyco/ionic-cloud/issues/16 will fix this issue.
