### ISSUE TITLE
Not able to receive notification on IOS production but received successfully on ios development

### ISSUE THREAD

**Issue by tynitin** [driftyco/ionic-cloud#120]
I have registered with Ionic cloud to use push notification services. Application that is registered has app id: 8a34049a
To test push notification I am running curl command
**curl -X POST -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eykiOiI0MTM4YzEyMi0xNTU0LTRmYmItYWJhMy1lZjgwMmVlZmRlMTgifQ.eOx8xeYq4qJy2AxLRldWHSQnooHTQvDHPhUbZ6ZIABA" -H "Content-Type: application/json" -d '{"tokens": ["2af6a5593b4300026df3a970e50385c9e9efbe623ad191d7676ed4f5baee5cb2"],"profile": "iosprod",    "notification": {        "message": "good message"    }}'  "https://api.ionic.io/push/notifications/"**

And response i am getting is

**{"meta": {"version": "2.0.0-beta.0", "status": 201, "request_id": "ac17301c-f77e-43e3-c368-e48ed6e8050f"}, "data": {"state": "enqueued", "created": "2016-12-23T04:02:49.155954+00:00", "app_id": "8a34049a", "status": "open", "config": {"tokens": ["2af6a5593b4300026df3a970e50385c9e9efbe623ad191d7676ed4f5baee5cb2"], "notification": {"message": "good message"}, "profile": "iosprod"}, "uuid": "fd24e2ec-6ca5-4763-8c84-6514f0f9d6c2"}}**

when i lookup this uuid in **https://api.ionic.io/push/notifications/fd24e2ec-6ca5-4763-8c84-6514f0f9d6c2/messages**
i am getting response
**{
   "data": [
      {
         "status": "error",
         "notification": "fd24e2ec-6ca5-4763-8c84-6514f0f9d6c2",
         "error": "UNKNOWN",
         "token": {
            "id": "864c54ff001850718bce150e606d7a97",
            "valid": true,
            "app_id": "8a34049a",
            "invalidated": null,
            "type": "ios",
            "created": "2016-12-23T04:01:06.289413+00:00",
            "token": "2af6a5593b4300026df3a970e50385c9e9efbe623ad191d7676ed4f5baee5cb2"
         },
         "created": "2016-12-23T04:02:49.470631+00:00",
         "user_id": null,
         "uuid": "b7341e29-5cfa-4820-8c3b-a01070f91257"
      }
   ],
   "meta": {
      "status": 200,
      "request_id": "9c9ce63d-2e7b-484e-c882-da71f6e9ca49",
      "version": "2.0.0-beta.0"
   }
}**
when i send message directly from **APN tester (available on app store)** my application is getting push notification instantly.
Please have a look into this as i have to deliver to this my client.

**Comment by tynitin** [comment]
Please help me soon as this is the only thing i am left with in my app. Else its ready to be used by client. And its really getting harder to understand client day by day.

**Comment by gbansal9** [comment]
I am also facing the same issue and i am not able to send push notification on production, on dev its working perfectly fine. Please help me in resolving this issue.

**Comment by ashishrawat044** [comment]
Same thing is happened with Me. If someone Knows then Please Help me out.

**Comment by shubhikhushi** [comment]
I am also facing the same issue. It worked fine on development but not able to send push notification on production environment. Please let me know the resolution as soon as possible.

**Comment by ankujjj** [comment]
Please share if any one get the solution of this issue. i am also facing same thing.

**Comment by tynitin** [comment]
Dear All,

i got the solution, after wasting my 8 good days with ionic and other stuff.
I was trying to upload p12 file exported by my certificate key in keychain.
But correct p12 file is --extract it from your certificate, not by your key.
And upload it to ionic, your current production version will work.

**Comment by gbansal9** [comment]
Thanks a lot tynitin. It worked for me too. :)

**Comment by tynitin** [comment]
Again i am facing problem in apple notifications
i am getting following error while checking the status of uuid i am receiving in curl reponse
{
   "data": [
      {
         "user_id": null,
         "uuid": "c0499b7e-3a90-41c7-8eee-20d5d94dfafa",
         "created": "2017-01-04T12:13:41.002403+00:00",
         "status": "error",
         "error": "APNS_BAD_DEVICE_TOKEN",
         "token": {
            "valid": false,
            "invalidated": "2017-01-04T12:13:41.950815Z",
            "token": "7c68fe666ed53b4e5b90c8f4066c260e9b6d86f459ac69ae88ef9062a3757897",
            "app_id": "8a34049a",
            "created": "2017-01-04T12:08:53.782935+00:00",
            "id": "6246075e9f0c890638a723f29b1fad00",
            "type": "ios"
         },
         "notification": "cc9ae71e-f143-492a-bfa5-144bc10a642c"
      }
   ],
   "meta": {
      "status": 200,
      "request_id": "9f6202ce-90b6-4324-c3fe-766e0b2558d4",
      "version": "2.0.0-beta.0"
   }
}

**Comment by TwinLight** [comment]
Hello, @tynitin. i would like to get clear instruction from you. 

here my distribution cert. (with expanded key)
<img width="545" alt="screen shot 2017-01-16 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/9023187/21973579/a1e63324-dbfc-11e6-8596-62f8ef858c6e.png">

which options?
1)I expend the cert, then select both `key` and `cert`, then export it to `.p12`
2)Export the `cert` only to `p12`
3) Eport the `key` only to `p12`

**Comment by tynitin** [comment]
Hi TwinLight,
You have to export the certificate as p12 file not as key of certificate. i.e. do not expand it and generate certificate after expanding this distribution.
personal suggestion: Ionic notification are not consistent, on iphone. Use onesignal.com notifications. As i have also switched to Onesignal. This is free also.

**Comment by TwinLight** [comment]
@tynitin , Thanks for your suggestion man

**Comment by organismen** [comment]
@tynitin You are my hero, at least for a week!
