### ISSUE TITLE
Ionic Auth 404 on Android, 200 on iOS/Browser

### ISSUE THREAD

**Issue by nicknasirpour** [driftyco/ionic-cloud#122]
Hi, I'm developing an Ionic-2 app, and I'm using the Ionic Auth module. When running the app in the browser or on my iOS device, everything works fine. However, when trying to login on my Android device using USB debugging, I get 404's from the api.ionic.io/auth/login endpoint with basic login, and when I hit the signup endpoint, it doesn't return anything.

**Comment by ericb** [comment]
Have you logged in on the other device correctly? Maybe you've used a different app id? I'd suggest inspecting the requests to see what differences there are.

**Comment by nicknasirpour** [comment]
Figured it out, there was a CSP error. Solved by including a Content Security Protocol meta tag in my header.
