### ISSUE TITLE
Problems with Push notifications on iOS in production

### ISSUE THREAD

**Issue by opiispanen** [driftyco/ionic-cloud#133]
After releasing our app for the iOS and Android, we have encountered problems with receiving push notifications on iOS.

The problem is only on the iOS version of the app and the notifications worked just fine in the dev environment for both iOS and Android. After troubleshooting the problem on the phone and our server, I noticed that the Ionic Cloud API actually gives strange errors for the iOS notifications.

This is one of many iOS examples from the Ionic cloud endpoint /push/notifications/:notification_id/messages:

`{
            "notification": "65340fd8-9db9-4bb9-a1fd-9573101b3771",
            "uuid": "587b54ca-4d4f-4e99-9669-926b05bac3a2",
            "error": "UNKNOWN",
            "token": {
                "valid": true,
                "invalidated": null,
                "type": "ios",
                "token": "[device_token]",
                "created": "2017-01-10T16:33:18.335736+00:00",
                "app_id": "[app_id]",
                "id": "3cfb57e633579718dadbeb56b44c3060"
            },
            "status": "error",
            "user_id": null,
            "created": "2017-01-11T18:51:08.811290+00:00"
}`

On android, same notification:
`{
            "notification": "65340fd8-9db9-4bb9-a1fd-9573101b3771",
            "uuid": "d7a69e13-ece7-47be-9354-15be009f60ad",
            "error": null,
            "token": {
                "valid": true,
                "invalidated": null,
                "type": "android",
                "token": "[device_token]",
                "created": "2017-01-08T10:33:30.784975+00:00",
                "app_id": "[app_id]",
                "id": "c94b8b8d4acad52537d8dd3bb43c5d8a"
            },
            "status": "sent",
            "user_id": null,
            "created": "2017-01-11T18:51:08.814746+00:00"
}`

The error message on the iOS doesn't say much, so we're a bit confused now how to proceed fixing this problem. Notice that I removed app_id and device tokens from the data..

**Comment by opiispanen** [comment]
I think this is related to my problem

https://github.com/driftyco/ionic-cloud-issues/issues/252

Why is there Ionic-cloud and Ionic-cloud-issues when you can put issues here?

**Comment by opiispanen** [comment]
We got iOS version to work in production by re-doing our certificates, for the third time (I guess), so be patient with them!

**Comment by Fuiste** [comment]
Apple can be really fickle with their certificates, which is really unfortunate.  

It looks like you solved the issue however, so I'm closing this one for now.  Let me know if it persists and we can take a closer look.
