### ISSUE TITLE
Notification Buttons

### ISSUE THREAD

**Issue by yigitbacakoglu** [driftyco/ionic-cloud#135]
Hi, 

As documented on phonegap push plugin, how can I set action buttons for the homescreen notifications?
here is an example notification from phonegap

```json
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "My title",
        "message": "My message.",
        "actions": [
            { "title": "Accept", "callback": "app.accept", "foreground": true},
            { "title": "Ignore", "callback": "app.ignore", "foreground": false}
        ]
    }
}
`

**Comment by Fuiste** [comment]
This is posisible using the `data` field in our schema, which allows you to send raw data directly to the plugin as opposed to using the fields supplied in the Ionic API.  

You can see where to place it in the schema definition of [this](http://docs.ionic.io/api/endpoints/push.html#post-notifications) endpoint.
