### ISSUE TITLE
Documentation mess

### ISSUE THREAD

**Issue by szuzul** [driftyco/ionic-cloud#14]
There is a mess in documentation on http://docs.ionic.io/docs/ for push service no ionic cloud is meshed and half of documentation steps are not correct. 
If you are trying to implement push service at this moment from ionic push documentation it is mission impossible.

**Comment by dwieeb** [comment]
Yes, we're aware. `ionic-cloud` is not released yet. We are currently working on new documentation. For now, if you'd like to test it and give some feedback, see this issue: https://github.com/driftyco/ionic-cloud/issues/3

**Comment by dwieeb** [comment]
@szuzul Our new docs are live: http://docs.ionic.io
