### ISSUE TITLE
platform.toLowerCase is not a function

### ISSUE THREAD

**Issue by nicobytes** [driftyco/ionic-cloud#140]
When I inject **Auth** in constructor. Generate this error:

![localhost-8100- iphone 5](https://cloud.githubusercontent.com/assets/7611944/22095566/e25094a2-dde3-11e6-881f-da01fcaafaa8.png)

**Comment by almothafar** [comment]
I have the same issue: 

```
Install the Device plugin: 'ionic plugin add cordova-plugin-device'
Zt @ ionic.cloud.min.js:1
n @ ionic.cloud.min.js:1
get @ ionic.cloud.min.js:1
e.markActive @ ionic.cloud.min.js:11
e.checkActivity @ ionic.cloud.min.js:11
(anonymous) @ ionic.cloud.min.js:11
ionic.cloud.min.js:11 Uncaught TypeError: e.toLowerCase is not a function
    at e.normalizeDevicePlatform (ionic.cloud.min.js:11)
    at e.markActive (ionic.cloud.min.js:11)
    at e.checkActivity (ionic.cloud.min.js:11)
    at ionic.cloud.min.js:11
```

Ionic 1.3.2, seems it is on web view only?

**Comment by cfjedimaster** [comment]
Just commenting that if anyone has a workaround, a temp hack, I'd definitely appreciate it.

**Comment by nphyatt** [comment]
Looks like a bug on our end. Publishing a fix right now. Should be out in a couple minutes.

**Comment by nphyatt** [comment]
Ok if you update to `0.9.1` for `@ionic/cloud-angular` or `0.15.1` for `@ionic/cloud` this should be resolved.
