### ISSUE TITLE
[ionic-push] Notification status API response has blank data

### ISSUE THREAD

**Issue by saurabh-jtg** [driftyco/ionic-cloud#143]
Hi, This is regarding **Push notification APIs**. The issue that I am facing is that notification status API is not returning status data each time. Sometimes it does, but mostly it is returning blank list in **"data"** key.

I am adding the actual cURL calls and received responses for reference.

Call to send notification-
```
curl -X POST -H "Authorization: Bearer <my_app_token>" -H "Content-Type: application/json" -d '{
    "tokens": ["fFXJhJFaRBs:APA91bEZoOnrbv2jEvP5VUOF7e7AOlRBJ8NOIsUm1FYBZAHdNzUIdcTGHxglVgpNl5tu9yGpOJTrxWLbLTh-obvXy_M5Ga9xECWpRdSUCA3DhuHlFzwYJ0rLPbalM77Sy0lT9W6CGq9n"],
    "profile": "<my_security_profile>",
    "notification": {
        "title": "t1",
        "message": "m1",
        "android": {
            "content_available": 1
        },
        "ios": {
            "content_available": 1
        },
    }
}' "https://api.ionic.io/push/notifications"
```
Response from this-
```
{
    "meta":{
        "status":201,
        "version":"2.0.0-beta.0",
        "request_id":"68a19ccc-e676-41f2-c17b-7a7714ee7c8f"
    },
    "data":{
        "status":"open",
        "uuid":"19d0fd9a-4c91-4d01-87d4-5d19e27c0ab2",
        "created":"2017-01-20T08:12:00.253298+00:00",
        "app_id":"<my_app_id>",
        "state":"enqueued",
        "config":{
            "tokens":[
                "fFXJhJFaRBs:APA91bEZoOnrbv2jEvP5VUOF7e7AOlRBJ8NOIsUm1FYBZAHdNzUIdcTGHxglVgpNl5tu9yGpOJTrxWLbLTh-obvXy_M5Ga9xECWpRdSUCA3DhuHlFzwYJ0rLPbalM77Sy0lT9W6CGq9n"
            ],
            "notification":{
                "message":"m1",
                "ios":{
                    "content_available":1
                },
                "android":{
                    "content_available":1
                },
                "title":"t1"
            },
            "profile":"<my_security_profile>"
        }
    }
}
```

Then using the uuid, call to retrieve status-
```
curl -X GET -H "Authorization: Bearer <my_app_token>" -H "Content-Type: application/json" "https://api.ionic.io/push/notifications/19d0fd9a-4c91-4d01-87d4-5d19e27c0ab2/messages"
```
Response from this-
```
{
    "meta":{
        "status":200,
        "version":"2.0.0-beta.0",
        "request_id":"f042ada6-de6c-492b-c9db-d9b83cb37452"
    },
    "data":[
    ]
}
```
Status/error data is crucial to my requirement and should be consistent. Please look into it and/or provide information if I am missing anything here.

**Comment by Fuiste** [comment]
Empty data means either no tokens specified were valid or no targets had tokens associated, which results in no messages (which house status) being created.  This is done so that users cannot be charged for pushes that would not be sent.

You can use [this](http://docs.ionic.io/api/endpoints/push.html#get-tokens-token_id) endpoint to check the status of a given token.

**Comment by saurabh-jtg** [comment]
@Fuiste Hi, Thanks for the reply.
We use the "error" in data to decide if the app was uninstalled from a device, so if we do not get the data, how can we do that? The **tokens** endpoint you referred does not provide that data.

**Comment by saurabh-jtg** [comment]
@Fuiste Any update on above comment?

**Comment by Fuiste** [comment]
I"m not sure what you mean.  If there were no valid tokens in a request, then no associated messages will be created and we cannot return information on them.

You can use the tokens endpoint above to check that a token is valid, but I'm not sure that using the `error` field on a push notification is the best way to track uninstalls of an app, as there's a number of reasons that a token can be marked invalid.

**Comment by saurabh-jtg** [comment]
Okay. Nothing about validity of tokens is mentioned in the docs.

Currently I am using data/error from notification status call to track un-installation. I understand that there may be multiple reasons for token to be invalid, but please note that the example I gave you was specifically for uninstalled tokens and no other error.

My main purpose here is to not check validity of token but to send a notification and get uninstallation status based on the specific error (**APNS_UNREGISTERED** (in case of iOS) or **GCM_INVALID_REGISTRATION** (in case of android)).

What are your further thoughts about it? Also let me know if we can discuss it on a more interactive channel (chat or call)?

**Comment by saurabh-jtg** [comment]
@Fuiste Any update?

**Comment by Fuiste** [comment]
At the moment, Ionic will not attempt to send messages to tokens that have been marked invalid.  This is to ensure that customers are not bitting their monthly rate limits as a result of invalid tokens.  It is also for this reason that I suggested tracking push errors may not be the best way to gauge uninstalls of your app, as tokens can be invalidated for a number of reasons and would no longer return those specific errors on the message level.

**Comment by johnparkerg** [comment]
@saurabh-jtg I've been struggling with the same and as far as I can tell (anecdotally) you get it marked as invalid once and then you just get nothing back.
