### ISSUE TITLE
What is the current version?

### ISSUE THREAD

**Issue by sebrojas14** [driftyco/ionic-cloud#160]
When I install it vía npm, always is installed version 0.14.1, but here in releases theres a 0.15.1 version

**Comment by dwieeb** [comment]
@sebrojas14 Make sure your `package.json` has the latest version before installing with npm. Take a look at [`npm update`](https://docs.npmjs.com/cli/update).

Also remember that for Ionic 1, you have to move the library into your `www/lib` folder: http://docs.ionic.io/setup.html#installation each time it's updated.
