### ISSUE TITLE
Deploy stopped working

### ISSUE THREAD

**Issue by Deadsoil** [driftyco/ionic-cloud#161]
Hi,

Deploy has stopped working today. I haven't changed anything. My app just no longer switches to the latest deploy. It downloads, extracts and restarts and shows the new build ID in console, but it is still the old build displaying.

I literally haven't changed one thing with my code. It just no longer displays the latest deploy. Checked on multiple devices.

`this.deploy.check().then((snapshotAvailable: boolean) => {
  if (snapshotAvailable) {
    this.deploy.download().then(() => {
      this.deploy.extract().then(() => {
        this.deploy.load();
      });
    });
  }
});`

I'm at a loss....

UPDATE: Just to be 100% sure I didn't make a mistake, I created a brand new project with only cloud and deploy and it is having the same issue. 

UPDATE 2: It seems that when I rebuild the app in xcode and load it on my phone it will download and display the first deploy I did.... Then after it will download and extract the new deploy but still displays the first one. Nothing in console suggests there was a problem. In fact console suggests it's pointing to the index file of the latest deploy ID. Keep in mind this is happening on my main project and a completely fresh project and only started happening this morning (Australian time).

**Comment by Deadsoil** [comment]
SOLVED: Sorry, this can be deleted... I discovered that ionic upload takes files from the /www folder not from the /src folder. Frustrating.

**Comment by piotrowski** [comment]
You should be able to close this by yourself actually.
