### ISSUE TITLE
Password reset fails when reset code has leading zeros.

### ISSUE THREAD

**Issue by acarbonellb** [driftyco/ionic-cloud#163]
Hi all,

I'm having some trouble with this feature.
All works OK if the code (the one that is sent by email) starts with non-zero, i.e. 123456.
But always that has leading zeros, i.e. 012345, the request fails with a 422 error.

Attached is the received response.

Thanks in advance,
Regards.

[passwordResetErrorJson.txt](https://github.com/driftyco/ionic-cloud/files/777195/passwordResetErrorJson.txt)

**Comment by ericb** [comment]
Looks like this was a misconfiguration on our end. Should be fixed now. 🍻

**Comment by acarbonellb** [comment]
Thanks!
