### ISSUE TITLE
Ionic Deploy - saving version binary info in https://apps.ionic.io not working.

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#17]
Not sure this is the correct place, but saving doesn't seem to work.

**Comment by dwieeb** [comment]
Can you inspect the response to the API call in Chrome's Network tab? It may shed more light on what's going on. There is a fair amount of validation server-side that is just missing client-side during this first pass of our beta UI. I do know the versions have to be semver.

**Comment by sagivf** [comment]
Why didn't I think of that :)
Looking at the response It's indeed a validation issue. The "note" can't be blank.
After adding it in, saving works.
It doesn't seem to be mandatory in the UI or doc so this is somewhat of a bug....

**Comment by dwieeb** [comment]
@sagivf I agree.

@perrygovier Do you think this could fit into what you're working on?

**Comment by sagivf** [comment]
@dwieeb Shall I rename the title or open a new bug?

**Comment by dwieeb** [comment]
New issue: https://github.com/driftyco/ionic-cloud-issues/issues/137

**Comment by all43** [comment]
Issue link is broken. Saving without note still doesn't work (1 year passed!)
