### ISSUE TITLE
Ionic Cloud rejecting tokens for custom auth

### ISSUE THREAD

**Issue by kshaaban-** [driftyco/ionic-cloud#175]
I'm facing a strange issue with Ionic Cloud Custom Authentication.

I have defined a shared secret and an endpoint in the application's auth settings.
When attempting to login/register, the inAppBrowser flow errors out with the following:

```json
{
    "meta": {
        "status": 400,
        "request_id": "abc8591a-81ca-4e7c-ceee-6b6d3426b4a7",
        "version": "2.0.0-beta.0"
    },
    "error": {
        "message": "Token not valid: Invalid JWT: JWT decode error occurred.",
        "link": null,
        "type": "BadRequest"
    }
}
```

The strange thing here is that:
- Using the shared key, I am able to decode & verify the cloud generated incoming token.
- Cloud throws aforementioned error upon redirecting the client to the `redirect_uri` with the `state` nonce and a new `token` (signed using the same shared key) authenticating the user.
- Using devtools/inspector on devices/emulators. I can see the inAppBrowser requests firing and being redirected properly. I was able to verify (using jwt.io) both incoming, and outgoing tokens against the shared secret and everything checks out.

I'm not sure if this is something I'm doing wrong (given that it things worked about 3 weeks ago), or if it's an issue with the specific app/settings on ionic.io (haven't tried on another app), or a cloud issue!

Below is my endpoint's code for reference:

```js
const Boom = require('Boom')
const co = require('co')
const config = require('config')
const jwt = require('jsonwebtoken')
const User = require('../../../models').User

module.exports = co.wrap(function *(ctx) {
  const queryParams = ctx.request.query
  const redirectUri = queryParams.redirect_uri
  const state = queryParams.state

  let incomingToken
  try {
    incomingToken = jwt.verify(queryParams.token, config.get('server.secret'))
  } catch (error) {
    throw new Boom.unauthorized()
  }

  const email = incomingToken.data.email || ''
  const password = incomingToken.data.password || ''
  const user = yield User.find({
    where: {
      email: email.toLowerCase()
    }
  })

  if(!user) {
    throw new Boom.unauthorized()
  }

  const isCorrectPassword = yield user.verifyPassword(password)

  if (!isCorrectPassword) {
    throw new Boom.unauthorized()
  }

  const outgoingToken = jwt.sign({
    'user_id': ''+user.id         // Must be string for ionic auth
  }, config.get('server.secret'))

  const url = redirectUri +
  '&token=' + encodeURIComponent(outgoingToken) +
  '&state=' + encodeURIComponent(state)

  ctx.redirect(url)
})
```

Thanks for all the awesome work!

**Comment by ericb** [comment]
At a quick glance this looks correct. Are you able to verify that the url is properly constructed or that the request that actually gets sent to our server has not been modified by some middleware?

**Comment by kshaaban-** [comment]
@ericb 

Absolutely, the generated url looks like:

```
https://api.ionic.io/auth/integrations/custom?app_id=XXXXXXXX&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImlhdCI6MTQ4ODMwMDI0MX0.k2Vy_03xWEul-e8Nbn0qVn9aInQQUso83XF0fgcooT4&state=cb6ca847e261906551543ac271288a49
```

And if I'm understanding this correctly, it is the client (mobile app) that makes this request through the inAppBrowser? So middlewares do not seem to be messing up with the redirect url (nor response headers)

Here's the 302 response coming out of the server:
```
GET /api/v1/users/ionic-auth?state=cb6ca847e261906551543ac271288a49&redirect_uri=https%3A%2F%2Fapi.ionic.io%2Fauth%2Fintegrations%2Fcustom%3Fapp_id%3Dee895186&token=~SNIPPED~TOKEN~
    HTTP/1.1
    host: localhost:5000
    upgrade-insecure-requests: 1
    accept-encoding: gzip, deflate
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    accept-language: en-us
    connection: keep-alive
    user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C89
    --
    HTTP/1.1 302 Found
    HTTP/1.1 302 Found
    Location: https://api.ionic.io/auth/integrations/custom?app_id=ee895186&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImlhdCI6MTQ4ODMwMDI0MX0.k2Vy_03xWEul-e8Nbn0qVn9aInQQUso83XF0fgcooT4&state=cb6ca847e261906551543ac271288a49
    Content-Type: text/html; charset=utf-8
    Content-Length: 509
    Date: Tue, 28 Feb 2017 16:44:01 GMT
    Connection: keep-alive
```

I can share the incoming token and a _temporary dummy_ secret to verify on http://jwt.io, but I'm not sure what the risks are (if any at all) for sharing the app_id publicly

**Comment by kshaaban-** [comment]
Quick update, I tried the following:

1. Created the most basic server and a new app on ionic.io
2. Cloned https://github.com/driftyco/custom-auth-examples and followed the curl steps in the README file

Both attempts were rejected by Ionic Cloud with the same error message regarding JWT token being invalid.

I'm starting to suspect an issue with ionic cloud servers, unless somebody can assert that custom auth was/is working for them since the past 48 hours!

**Comment by ericb** [comment]
Thanks for trying out a fresh project @kshaaban- I'm looking into this now.

**Comment by ericb** [comment]
Hey @kshaaban- I've replicated the issue and we're looking into it now.

**Comment by ericb** [comment]
Okay, it should be resolved for you @kshaaban- 

If you're interested in the details, this was due to clock skew between servers. The jwt library we use in the auth examples for node adds an `iat` "Issued At" timestamp by default which was slightly in the future compared to our servers. We've added some leeway timing to account for this.

Cheers 🍻

**Comment by kshaaban-** [comment]
Thanks a bunch!
