### ISSUE TITLE
Ionic Cloud and Instagram OAuth

### ISSUE THREAD

**Issue by FlawaCLV** [driftyco/ionic-cloud#177]
I am using Ionic Cloud to login with Instagram,

`this.auth.login('instagram').then(result: {signup: boolean, token: string} => { });`

But when I call the API with `access_token` parameter being the token I received from the login (or  `this.auth.getToken()`) I get a 400 error.

Endpoint: `https://api.instagram.com/v1/users/{USER_ID}/media/recent/?access_token={ACCESS_TOKEN}`

Error thrown:

```json
{
    "meta": {
        "error_type": "OAuthAccessTokenException",
        "code": 400,
        "error_message": "The access_token provided is invalid."
    }
}
```

Any idea ?

**Comment by ericb** [comment]
The token that you have received is the ionic auth token. We do not return the instagram access token.
