### ISSUE TITLE
Push notification stuck in "enqueued" state

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud#181]
Hey there!

I'm trying to send push notifications in ionic 2, and after following the docs step-by-step, I am still not able to receive notifications.  They seem to be getting created successfully (as shown in the response JSON below), but my device never receives them.  I am testing on an Android device and have tested sending notifications through the API as well as the dashboard, and both get stuck in "enqueued".  Any help would be much appreciated.

Response after running `https://api.ionic.io/push/notifications`

```{
  "data": [
    {
      "app_id": "myAppId",
      "status": "locked",
      "created": "2017-03-04T07:01:55.448699+00:00",
      "state": "enqueued",
      "uuid": "35a77793-2aab-4b9e-a239-1a478855be7a",
      "config": {
        "profile": "dev",
        "tokens": [
          "MY_USER_TOKEN"
        ],
        "notification": {
          "message": "Roadie liked your Deed"
        }
      }
    },
    {
      "app_id": "myAppId",
      "status": "locked",
      "created": "2017-03-04T06:59:51.158042+00:00",
      "state": "enqueued",
      "uuid": "df66112b-e858-4e98-a9ba-f2efe2a69b1f",
      "config": {
        "profile": "prod",
        "tokens": [
          "MY_USER_TOKEN"
        ],
        "notification": {
          "message": "Roadie commented on your Deed: what a great picture"
        }
      }
    },
    {
      "app_id": "myAppId",
      "status": "locked",
      "created": "2017-03-04T06:44:41.269157+00:00",
      "state": "enqueued",
      "uuid": "6a4f1dac-c9a7-494c-985f-5cfa94e6e927",
      "config": {
        "profile": "prod",
        "tokens": [
          "MY_USER_TOKEN"
        ],
        "notification": {
          "message": "Roadie commented on your Deed: ok here's another test comment"
        }
      }
    },
    {
      "app_id": "myAppId",
      "status": "locked",
      "created": "2017-03-04T06:05:22.082500+00:00",
      "state": "enqueued",
      "uuid": "0aeb6f84-9725-4488-86df-eacd84fb9fdb",
      "config": {
        "send_to_all": true,
        "profile": "prod",
        "notification": {
          "message": "Get 150% off!",
          "ios": {
            "message": "Get 150% off!",
            "priority": 10,
            "title": "Test Push"
          },
          "payload": {},
          "android": {
            "message": "Get 150% off!",
            "priority": "high",
            "title": "Test Push"
          },
          "title": "Test Push"
        },
        "query": {}
      }
    }]
}

**Comment by joshgarwood** [comment]
Ok, I got this to work today.  It may have been an issue with the users token being expired.  So to anyone else who may have this issue, make sure the recipients token is current... it needs to be saved each time you register the device

**Comment by joshgarwood** [comment]
This worked very briefly for me (I didn't change anything). And then suddenly, it stopped and all my messages are "enqueued" again.  After doing more research, it seems as though a number of users are experiencing this problem... Is Ionic Push operational at the moment?

**Comment by ericb** [comment]
Yup, everything is working as intended. You can check the status of services using [status.ionic.io](http://status.ionic.io). `enqueued` is a normal state and it means that hte notification has been past on for processing on individual messages. Check out the note in our [docs](http://docs.ionic.io/services/push/#checking-notification-status).

**Comment by joshgarwood** [comment]
Thanks @ericb , but I'm afraid everything is not working as intended.  I've read the docs quite thoroughly and understand that `enqueued` is a normal state.  However, my notifications have been `enqueued` for over 48 hours, so something is not right.  This has been reported on a number of other occasions as well.  So even if it's a problem with developers doing something incorrect, it would seem as though the docs are missing something, because many people are experiencing the same thing as me.  Please reopen this :)

https://forum.ionicframework.com/t/ionic-2-push-notification-doesnt-send-but-has-state-enqueued-and-status-locked/62992

https://forum.ionicframework.com/t/ionic-io-push-notifications-not-received/47207

https://forum.ionicframework.com/t/ionic-push-not-working-on-ios-only-third-party-app-can-send-notification-but-ionic-can-not/50593

**Comment by ericb** [comment]
Sorry, to be more clear, the enqueued state is long-lived. There is no further state beyond enqueued. You need to check the statuses of the individual messages that were sent with the notification as stated in the link I previously provided. Here is the direct link to the API endpoint where you can check this: [notification messages listing](http://docs.ionic.io/api/endpoints/push.html#get-notifications-notification_id-messages)

**Comment by joshgarwood** [comment]
Ahh ok, that is very helpful; sorry for misunderstanding.  That said, it could save a lot of confusion (and time for yall), if that GCM error could be returned in the `/post/notifications GET` result.
