### ISSUE TITLE
Better "enable google+ api" documentation and error handling.

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#19]
Got this view after logging in:
![image](https://cloud.githubusercontent.com/assets/1857466/16710980/1acb6268-464e-11e6-88c9-6de34b1a0be4.png)

Seems to work after I enable google+ api , perhaps it needs adding to the docs.
![image](https://cloud.githubusercontent.com/assets/1857466/16710984/3d971ac6-464e-11e6-895c-94eaf62586c3.png)

**Comment by dwieeb** [comment]
@sagivf We're doing a massive rewrite of our documentation to ensure that it is current, clear, and accurate. @devnetics is looking into social provider authentication to provide better error messages when something like this goes wrong.

**Comment by sagivf** [comment]
@dwieeb Thanks, no worries, If you can catch it that would be good, but if the setup steps are accurate I don't think this should be an issue.

**Comment by SteveKennedy** [comment]
@dwieeb @sagivf Is there a work around for this?  I get this error no matter what I try, when authenticating via Google.

**Comment by SteveKennedy** [comment]
For me, I got this error when I didn't have Google API's enabled in the Google API console.

**Comment by sagivf** [comment]
Yes @SteveKennedy I think the title is confusing, I meant this should be added to the docs and return a better error.

**Comment by sagivf** [comment]
closing this so to remove noise

**Comment by devnetics** [comment]
@sagivf I've added a few tasks in our backlog related to docs cleanup and better error handling (for this and other auth flows), feel free to ping me on Ionic Worldwide with any other feedback.
