### ISSUE TITLE
Storing the user after authentication

### ISSUE THREAD

**Issue by Maistho** [driftyco/ionic-cloud#2]
Ionic.Auth will store my authentication if I tell it to (remember == true), which seems to work fine.

The actual user is *not* stored unless I manually run `user.save()` afterwards.
If I reload the app without calling `user.save()` it leads to a scenario where `user.isAuthenticated()` returns true at the same time as `user.isAnonymous()`, which is a bit confusing.

**Comment by ericb** [comment]
Ah okay. This is because we only currently save the user details on device when `save` is called, but we should be storing them after a successful authentication to avoid this scenario.

ping @dwieeb - Perhaps we could implement a local-only save which can be called upon successful authentication.

**Comment by dwieeb** [comment]
The local save is already implemented. It just needed to be called upon successful login.

Thanks for the report, @Maistho!
