### ISSUE TITLE
Does Ionic Cloud build environment support plugin hook scripts?

### ISSUE THREAD

**Issue by dpa99c** [driftyco/ionic-cloud#200]
Does the build environment on the Ionic Cloud servers support [plugin hook scripts](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#hook)?

I'm asking because of [this issue](https://github.com/dpa99c/cordova-custom-config/issues/112) raised against [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) which is a plugin which is comprised solely of hook scripts.

**Comment by piotrowski** [comment]
Unfortunately not, see https://docs.ionic.io/services/package/#hooks
