### ISSUE TITLE
No promise resolution when user closes social provider window.

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#21]
Clicking
![image](https://cloud.githubusercontent.com/assets/1857466/16711031/f6c2a88e-464f-11e6-9a05-eb63c7deb928.png)

Will get your app flow stuck since there is no result.
![image](https://cloud.githubusercontent.com/assets/1857466/16711033/1a0db7a2-4650-11e6-9714-a554161a7ad3.png)

**Comment by sagivf** [comment]
@devnetics @dwieeb - hope i'm not stepping any bounds, but shouldn't this be in the beta release milestone? https://github.com/driftyco/ionic-cloud/milestone/1

**Comment by dwieeb** [comment]
Hi @sagivf. Apologies for the slow turnaround. I believe this was fixed in https://github.com/driftyco/ionic-cloud/commit/985d2e9ddf0459383e857acf21a6ad06b99e580a.

I am now **rejecting** the promise if the InAppBrowser is closed before successful authentication. I will have a release out soon!
