### ISSUE TITLE
Social login not "remembering" user credentials

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#23]
After login out and in - you have re login to Facebook every time.

When I used http://ionicframework.com/docs/v2/native/facebook/ in a different app, it remembered the user credentials when login into Facebook, and the user doesn't have to go trough the login again (lots of users doesn't remember their credentials).

Not sure this can be achieved in the current constellation, maybe through some sort of api integration with the app developer.

**Comment by dwieeb** [comment]
@sagivf The Facebook dialog opens when `auth.login('facebook')` is called and the user is prompted to login every time. We're not specifying an `auth_type` (see https://developers.facebook.com/docs/facebook-login/reauthentication) so I'm assuming the Facebook dialog just assumes you want to re-authenticate every time. I'm not sure if we want to remember the user credentials by default, but I think it'd be smart to have the option for it. 

Thoughts?

**Comment by sagivf** [comment]
Not sure a fully get this, but in the browser if you are signed in to facebook, any site using facebook OAuth  will not require you log in to facebook. If you logout on any window only then will you need to login. This behaviour is the same when you use the native facebook login.

Also it says that the reauthentication is meant for cases where there is sensative data that needs an extra password validation - 

![image](https://cloud.githubusercontent.com/assets/1857466/17415086/e3f45a2c-5a90-11e6-93c9-1199b8cfa013.png)


![image](https://cloud.githubusercontent.com/assets/1857466/17415060/c64366da-5a90-11e6-8bf9-ef8834d6847e.png)

**Comment by dwieeb** [comment]
@sagivf Okay, it makes sense to remember them and not force a re-login.

**Comment by dwieeb** [comment]
I will do this for the milestone.

**Comment by sagivf** [comment]
@dwieeb The more I think about it the more I think this is important.
Users that have to insert there credentials might easily prefer to just use a regular signup or forget about the app altogether. Ideally using the native facebook app would be best but this probably not possible so at least sharing the browsers mechanism would be good.

Haven't fully investigated the technical details but this is defiantly important.

**Comment by SteveKennedy** [comment]
I agree about this importance. I think I'm running into this issue. I'm developing a new app using Ionic 2, TypeScript 2, and Angular 2.  When calling auth.login("facebook") - each and every time - it forces a new login screen.  Same for Google. My app users would hate me.  :)  I'm hoping to down play logging in via the app/email/basic.

**Comment by devnetics** [comment]
@sagivf @SteveKennedy Please note I'm working on a fix for this and should have it updated shortly!

**Comment by dwieeb** [comment]
@sagivf @SteveKennedy It's definitely possible for us to provide a login method with the native Facebook app (with the [cordova-plugin-facebook4](https://github.com/jeduan/cordova-plugin-facebook4) plugin of course) for Ionic Authentication. We just went the InAppBrowser route because it was faster/easier/whatever.

I'll think on this.

**Comment by SteveKennedy** [comment]
Thanks for your hard work. This is all new to me, so I don't entirely know what I'm saying. :) 

I don't entirely know the difference between the user experiences - between using inAppBrowser vs the Cordova plugin.  Ideally, I would want something seamlessly native looking.  I assume that's with the facebook4 plugin. 

The inAppBrowser isn't a bad experience.  Except that it asks me to login to FB/Google with credentials, even though the rest of my phone apps somehow don't need to ask for those credentials.  They somehow use credentials from the phone/apps, without having to ask for them.

**Comment by dwieeb** [comment]
@SteveKennedy Yup, the native experience would come with that plugin, just like the rest of the apps with social logins.

@sagivf @SteveKennedy We're going to try to implement Facebook authentication using cordova-plugin-facebook4 for this milestone. This should give us what we want. 

Now, no more scope creep! 😆

**Comment by dwieeb** [comment]
So we're actually going to go live with the current InAppBrowser implementation, but we have [a milestone](https://github.com/driftyco/ionic-cloud/milestone/2) for native social login in the Cloud Client that @devnetics and I will be putting together in the coming weeks, hopefully.
