### ISSUE TITLE
null value for in users custom data field brakes login

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#24]
How to reproduce: 
Save a custom field (lets say "phone") with the value of `null`.
Try to login you will get - 

![image](https://cloud.githubusercontent.com/assets/1857466/17320687/7b851aa2-589d-11e6-993e-b3c361a1331b.png)

**Comment by sagivf** [comment]
I guess the api should either prevent saving a null value or allow fetching one.

**Comment by dwieeb** [comment]
Thanks, @sagivf!
