### ISSUE TITLE
Error logging in with Ionic CLI

### ISSUE THREAD

**Issue by makdas** [driftyco/ionic-cloud#25]
I cant upload my build using the cli command "ionic upload" anymore. 
I've uninstalled/reinstalled both cordova and ionic.

Console output:
Error logging in
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.7.16)
Your system information:
Cordova CLI: 6.3.0
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS:
Node Version: v4.4.1

**Comment by ericb** [comment]
Have you tried logging in directly `ionic login` or verifying that your email / password works on https://apps.ionic.io

**Comment by makdas** [comment]
I forgot to mention, yes i can log in with the details online no problem... Currently logged in.

**Comment by makdas** [comment]
I've included my username and password so anyone can test and see its working, even though the cli says its incorrect.

$ ionic io
No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

**Email: info@digitalbeyond.co.za
Password: githubpass
Email or Password incorrect. Please visit https://apps.ionic.io for help.**

Invalid command (CLI v2.0.0-beta.36)

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v4.4.1

**Comment by dwieeb** [comment]
Tried the exact command above with your username and  password.

```
$ ionic io
No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: info@digitalbeyond.co.za
Password: githubpass
Logged in! :)

Invalid command (CLI v2.0.0-beta.36)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6
ios-sim version: 5.0.2
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

I was logged in successfully, but the command failed.

Try deleting the `.ionic` folder in your home directory?

**Comment by makdas** [comment]
after i deleted the .ionic folder.

$ ionic upload
No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create a one at: https://apps.ionic.io/signup

Email: info@digitalbeyond.co.za
Password: githubpass
Error logging in
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.7.16)
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS:
Node Version: v4.4.1

and the new .ionic folder has a ionic.confiq file, content:
 {
  "lastVersionChecked": "1.7.16",
  "versionCheck": 1470847197369
}

This is from my windows machine. I get the same error log if I run this command from my macbook...
Tried diffrent .io accounts asswell so  really out of options at the mom

**Comment by dwieeb** [comment]
You don't have a proxy or anything set up, do you? What's the output of:

```bash
echo $PROXY
```

```bash
echo $http_proxy
```

**Comment by makdas** [comment]
no proxy setup no...

**Comment by dwieeb** [comment]
Try `ionic login --email "info@digitalbeyond.co.za" --password "githubpass"`

**Comment by makdas** [comment]
$ ionic login --email "info@digitalbeyond.co.za" --password "githubpass"
Error logging in

I've downgraded to 1.4, uprgraded to ionic 2 beta, uninstalled/reinstalled. Just won't log in.

**Comment by makdas** [comment]
I've finally managed to login and start uploading.  The solution: Used my phone's internet instead of my home internet and it started working again.... so what do i need to tell my isp in order for my home internet to connect with ionic io ?

**Comment by dwieeb** [comment]
Seems very strange indeed. If you find the cause, please post to this issue in case someone else has this problem.

**Comment by yenteck** [comment]
i have the same problem 

_To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: "n.yenteck@gmail.com"
error:   Invalid input for Email:
Email: n.yenteck@gmail.com
Password: 
Email or Password incorrect. Please visit https://apps.ionic.io for help.
Initializing app with ionic.io....
Error initializing app: TypeError: Cannot read property 'map' of undefined_

**Comment by genaro722** [comment]
@yenteck try chance the VPN or upload by 3G network with you Smartphone.

**Comment by cfjedimaster** [comment]
I just hit this too.

**Comment by cfjedimaster** [comment]
Ok, I can verify that I had used the wrong password, so for me, the issue is that the error isn't reported right.

**Comment by amad4biz** [comment]
I hit the same error, however, i can login on the website fine.

**Comment by tshesko1** [comment]
Was unable to connect directly with:
ionic io init

TRY
ionic login
ionic io init
