### ISSUE TITLE
$ionicUser  is not defined

### ISSUE THREAD

**Issue by Alkasih** [driftyco/ionic-cloud#27]
Dear the team, 

I tried the migration guide, but not too far I step in, I got the error message. 

ionicAuth is not defined
ionicUser is not defined

**Comment by dwieeb** [comment]
Gonna need more info/code examples. If that's truly the error you're getting, you probably need to use `$ionicAuth` and `$ionicUser`, not `ionicAuth` and `ionicUser`. The dollar sign is required because that's the name of the angular service.

**Comment by Alkasih** [comment]
First in the app I initialize the ionic

.config(function($ionicCloudProvider) { $ionicCloudProvider.init({ "core": { "app_id": "YOUR-APP-ID" } }); })

And then in the app.js, I want to check if the user is authenticate or not

var user = $ionicUser; //just checking if $ionicUser is called, but it is undefined.

if($ionicAuth.isAuthenticated()) //$ionicAuth is undefined

**Comment by dwieeb** [comment]
@Alkasih Did you inject the `$ionicUser` and `$ionicAuth` service? Take a look at https://docs.angularjs.org/guide/di.

**Comment by Alkasih** [comment]
Not, I didn't do that. Should I? Yes, I guess. Sorry forget it. 

One more question, please. The only reason that bring me to this migration is because of push.unregister(); is always give me the server responded with a status of 422 (UNPROCESSABLE ENTITY).

I mean can you ensure me if I migrate here than push.unregister() will work as expected?

**Comment by dwieeb** [comment]
The `ionic-platform-web-client` is being deprecated. We are now focussing on this Ionic Cloud client going forward. If something doesn't work as expected, we will fix it here. I know for a fact I have already fixed that `push.unregister()` issue, but let me know if you encounter any other issues.
