### ISSUE TITLE
ReferenceError: Promise is not defined. 

### ISSUE THREAD

**Issue by Alkasih** [driftyco/ionic-cloud#29]
`$ionicAuth.login('basic', detail, option).then(success, failure);`

It gets me that promise is not defined when I test the app on real device. On browser, I didn't find this error.

**Comment by dwieeb** [comment]
@Alkasih `Promise` is expected to exist in the environment. If it does not, you'll need to polyfill it. See the [migration guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide) for more info.

That being said, however, I think we can polyfill `Promise` for angular 1 by using angular promises ([like so](https://gist.github.com/robianmcd/8f04507acd014b57b95a)). I'll look into this. Thanks for bringing this to my attention.

**Comment by Alkasih** [comment]
I have tried to `npm install es6-promise` in my project, and then add `require('es6-promise').polyfill();` in the very beginning of my gulpfile. But it still doesnt help. Can you please help me to how fix the probelm? Do I need to add [https://gist.github.com/robianmcd/8f04507acd014b57b95a](url) to my project manually?

**Comment by dwieeb** [comment]
Your gulpfile? You need to add it into your Ionic app, not your build configuration file...

bluebird might have better documentation for browser support (if you don't want to mess with CommonJS): http://bluebirdjs.com/docs/install.html

No, don't add that gist to your project.

**Comment by Alkasih** [comment]
> You need to add it into your Ionic app
In what file I need to add this? In the app.js file? And how to reference it? 

I tried this in my auth.js controller

`var Promise = require('es6-promise').polyfill();`

It says that `require ` is not defined. 

I have also installed the bluebird and reference it in the gulpfile.js in my project but still it doesn't fix it.

**Comment by dwieeb** [comment]
Remove `es6-promise`. Add this line to your `index.html` file:

```html
<script src="//cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js"></script>
```

**Comment by Alkasih** [comment]
<script src="//cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js"></script>
<script src="http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js"></script>


I tried both of them one by one, but still no help. :(

**Comment by Alkasih** [comment]
It helps. I forgot the the colon before the double dash `//`. Thank you for the workaround.

**Comment by dwieeb** [comment]
I'll try to polyfill angular 1 promises on our end so the `<script` workaround isn't necessary.

For Angular 2 apps, a polyfill will be required.

**Comment by gsdiama** [comment]
Thank you, it was really helpfull, finally I solved the error!
