### ISSUE TITLE
The option argument is required in register 

### ISSUE THREAD

**Issue by Alkasih** [driftyco/ionic-cloud#30]
```
$ionicPush.register().then(function(token) {
  return $ionicPush.saveToken(token);
});
```

What kind of options are needed here?

**Comment by dwieeb** [comment]
`register()` takes no arguments. What error are you getting?

**Comment by Alkasih** [comment]
`The options argument is required` 

And it occured in the line of `$ionicPush.register`.

**Comment by Alkasih** [comment]
```
            $ionicAuth.signup(detailedLogin).then(function(newUser) 
              {
                var options = {'remember' : true};
                console.log('signup worked ok, here is the new user '+JSON.stringify(newUser));
                console.log(user);


                $ionicAuth.login('basic', detailedLogin).then(function() {

                  //$ionicPush.register(function(token) {
                  $ionicPush.register().then(function(token){

                    console.log("My Device tokensss:",token.token);
                    return $ionicPush.saveToken(token); 

                    user.migrate();

                    user.save();
                  });

```

**Comment by Alkasih** [comment]
This is my full code


`            $ionicAuth.signup(detailedLogin).then(function(newUser) 
              {
                var options = {'remember' : true};
                console.log('signup worked ok, here is the new user '+JSON.stringify(newUser));
                console.log(user);


                $ionicAuth.login('basic', detailedLogin, options).then(function() {

                  //$ionicPush.register(function(token) {
                  $ionicPush.register().then(function(token){

                    console.log("My Device tokensss:",token.token);
                    return $ionicPush.saveToken(token); 

                    user.migrate();

                    user.save();
                  });
`

**Comment by Alkasih** [comment]
How do you put the detail.custom to the register user? Would it be the options that is needed?

**Comment by Alkasih** [comment]
Unhandled rejection Error: The options argument is required.
    at new PushNotification (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:27:15)
    at Object.module.exports.init (file:///android_asset/www/plugins/phonegap-plugin-push/www/push.js:260:16)
    at file:///android_asset/www/lib/ionic.cloud.min.js:1:31247
    at t.once (file:///android_asset/www/lib/ionic.cloud.min.js:1:24550)
    at t.register (file:///android_asset/www/lib/ionic.cloud.min.js:1:31177)
    at file:///android_asset/www/js/services/common/auth.js:290:40
    at r (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13044)
    at i._settlePromise (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14548)
    at i._settlePromises (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15878)
    at r._drainQueue (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3148)
    at r._drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3209)
    at drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1238)
    at MutationObserver.<anonymous> (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:29699)

**Comment by Alkasih** [comment]
Hi can give me a quick respond of this, please?

**Comment by Alkasih** [comment]
It always said that GCM project number is not found. 


I have set it up here: 

.config(function($ionicCloudProvider) {
  $ionicCloudProvider.init({
    "core": {
      "app_id": "YOUR-APP-ID"
      "sender_id": "GCM Number"
    }
  });
})

I also have tried     `  "gcm_key": "GCM Number"`


But none of them fix that. 


I even have tried to re-run  `ionic config set gcm_key <your-gcm-project-number>`

**Comment by Alkasih** [comment]
I have a deadline tomorrow for this app to be lauched in a workshop, it's been 24 hours I am not sleeping just to `push.unregister()` problem.

**Comment by Alkasih** [comment]
The documentation is not fully describe how to set it, untill I look at the commit message and found this: 


```
      'core': {
        'app_id': '1234abc'
      },
      'push': {
        'sender_id': 'sender_id_123'
      }
```

**Comment by dwieeb** [comment]
@Alkasih You're using an undocumented beta version, as the Migration Guide says at the top. This won't be the first thing you encounter that's different between the cloud client and ionic-platform-web-client. 

Our new documentation is coming soon.

For now, I've updated the config example to include that config format.
