### ISSUE TITLE
payload on push notification

### ISSUE THREAD

**Issue by Alkasih** [driftyco/ionic-cloud#31]
Hi, can you show us how to go to state on push receive? 

This is how I call it in php, but how to handle it in the app?
```

		$data = array(
		                  'emails' => $email, 
		                  'profile' => 'testing',
		                  'notification' => array('message' => $msg, 'payload' => array('$state' => $stating, '$stateParams' => $statingParam))
		                  );
 

```
		$content = json_encode($data);

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_POST, TRUE);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
		'Content-Type: application/json',
		'Authorization: Bearer eyJ....'
		));
		$result = curl_exec($ch);
		curl_close($ch);		

```
```

**Comment by Alkasih** [comment]
I am able to send the payload with this: 

```
  $ionicEventEmitter.on('push:notification', function(notification) {
      // handle notification here
      
      console.log(notification);
      console.log(notification["message"]);
      console.log(notification.message);
      console.log(notification["message"]["payload"]["$state"]);
      console.log(notification["message"]["payload"]["$stateParams"]);
      console.log(notification.message.payload);
      if(notification["message"]["payload"]["$state"]) {

        //console.log(notification["$state"]);
        //console.log(notification["$stateParams"]);

        //prompt the user to switch
        navigator.notification.confirm("You have a new chat - go to it?", function(btn) {
          if(btn === 1) {

            //$state.go('app.company.shiftpubl.chat', {personID: reqId, ProductID: prodId})

            $state.go(notification["message"]["payload"]["$state"], notification["message"]["payload"]["$stateParams"]);
          }
        },"New Chat!")
      }

      return true;
  });
```

But still it can't open the target state.

**Comment by Fuiste** [comment]
@Alkasih which version of the `ionic-cloud` are you using in this example?

In addition, are you using the `cloud-angular` integration?

**Comment by Alkasih** [comment]
I download this version from here. 


I am just affraid if this has something to do with my `$rootScope.$on("$stateChangeStart"` : 


Here is my full code in the app.js:


```
  $ionicEventEmitter.on('push:notification', function(notification) {      
      if(notification["message"]["payload"]["$state"]) 
        {
            $state.go(notification["message"]["payload"]["$state"], notification["message"]["payload"]["$stateParams"]);
        }
      return true;
  });

``` 


Under this `$ionicEventEmitter`, I also have `$rootScope.$on("$stateChangeStart"` 

```
  $rootScope.$on("$stateChangeStart", function(event, toState, toParams, fromState, fromParams){
    $ionicLoading.show({
      template: 'Loadingss...'
    });

    if(!toState.authenticate && AuthService.isLoggedIn())
      {
          $state.transitionTo("app.profile");
          event.preventDefault();  
      }

    else if(toState.authenticate && !AuthService.isLoggedIn())
      {
        $state.transitionTo("app.auth");
        event.preventDefault(); 
      }

  });

```


I am wondering if `$stateChangeStart` overlap the ` $ionicEventEmitter`. 

Can you suggest me some workaround, and figure out what is the problem, please. 

Many thanks in advance.

**Comment by Alkasih** [comment]
What is `cloud-angular` for btw? I am able to receive the notification. The matter now is only it doens't change the state on the payload.

**Comment by dwieeb** [comment]
@Alkasih `cloud-angular` is for Ionic 2. You won't need to install it for your app.

Is `notification["message"]["payload"]["$state"]` actually defined and what you expect? If you're getting the value you're expecting, then this question is better suited for the [Ionic Forum](https://forum.ionicframework.com/), as it doesn't relate to the Ionic Cloud or the Cloud Client. It relates to the UI Router of angular 1 and the Ionic Framework.

**Comment by Alkasih** [comment]
Sometime it defined the value as expected, but sometime it is not. Weird behaviour.

**Comment by Alkasih** [comment]
And now there is one type of log I got in the browser when the notification is received: 

`Resource Interperated as Script but transferred with MIME type text/plain `

This log only appear when I tap the notification. It doesn't appear if I open the app without the notification.

**Comment by Alkasih** [comment]
Well, I am stuck here. No the `$ionicEventEmitter` show at all right now.

**Comment by Alkasih** [comment]
No Answer? I think that this migaration still has not complete yet?

**Comment by Alkasih** [comment]
The problem is my `$ionicPlatform.ready ` is never firing while I put the even emitter inside it. Makes me crazy for three days.
