### ISSUE TITLE
Failure while building the project environment

### ISSUE THREAD

**Issue by jarodms6** [driftyco/ionic-cloud#32]
Ionic Package
Android builds were working ok yesterday (8/18).

Now I'm receiving this error right away for Android builds:
"Failure while building the project environment"
That is all the error contains

iOS builds are working though.

**Comment by Alkasih** [comment]
Have you tried to remove the platform first and add it again?

**Comment by dwieeb** [comment]
@jarodms6 Can you give it another try? It should be working now.

**Comment by jarodms6** [comment]
Thanks @dwieeb ! Working now!

**Comment by rockertux** [comment]
@dwieeb I'm getting the same error, trying to build an iOS package, after working around driftyco/ionic-cli#1166 and driftyco/ionic-cli#1134.
