### ISSUE TITLE
is typing signal in ionic-cloud exist?

### ISSUE THREAD

**Issue by Alkasih** [driftyco/ionic-cloud#34]
Hi, I see that you have typing api in this version. I am just wondering if this will be implemented in the push chat/message function. 

Can you please write a little documentation how to implement this? I want this. Thanks.

**Comment by dwieeb** [comment]
What are you referring to?

**Comment by Alkasih** [comment]
Like any chatting app, when someone is replying our message, there would be an icon that show us that user is typing. And I see that you have this in the folder: [https://github.com/driftyco/ionic-cloud/tree/master/typings](url)

**Comment by dwieeb** [comment]
Those are Typescript type definition files. They aren't related to a chat feature.

**Comment by Alkasih** [comment]
Upss, I am sorry. But can you give me an idea how to have this in ionic?

**Comment by dwieeb** [comment]
This is a question more suited for the [Ionic Forums](https://forum.ionicframework.com/), not the client for the Ionic Cloud.
