### ISSUE TITLE
Password reset issues

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#35]
Tried using both strategies with some problems. wasn't able to receive an email.

1) Using the hosted form with `InAppBrowser` and `auth.passwordResetUrl` , got a 500 with an existing user.
![image](https://cloud.githubusercontent.com/assets/1857466/17931051/19d1b1ea-6a12-11e6-81f2-a6dc82c4d423.png)

2) Using mu own password reset form.
- with a valid email:
![image](https://cloud.githubusercontent.com/assets/1857466/17931125/6aa785fe-6a12-11e6-8caf-f5f285024ec3.png)

- using a non existent email:
It gets a success. If we are trying to prevent email fishing. Is that the case or should this have returns an error.

![image](https://cloud.githubusercontent.com/assets/1857466/17931146/8cd45b5c-6a12-11e6-80d6-55613bd99bd0.png)

**Comment by devnetics** [comment]
Hey @sagivf We identified the issue behind your error and fixed it on our end. Let me know if you have any further trouble. 

And yes it should always return a 204.

**Comment by sagivf** [comment]
Thanks @devnetics - works nicely for the hosted options.
For the custom form I get a "entry code" in the email - is that still in development?

Also the "change password" form opened from the email is nice but is not very responsive on my mobile device.

**Comment by dwieeb** [comment]
@sagivf The "entry code" (really it's a _reset code_) must be entered manually by the user at this time. Ultimately I think we'd like to do some work with deep linking and even authenticator plugins, but we need to prioritize some other things, first.

@devnetics has a task to make the hosted forms mobile friendly.

**Comment by sagivf** [comment]
@dwieeb where does he have to use it  "manually"? Is it his new password?

**Comment by sagivf** [comment]
@sorry for the confusion - all is well 👍
