### ISSUE TITLE
Facebook Native Login

### ISSUE THREAD

**Issue by devnetics** [driftyco/ionic-cloud#36]
Add facebook native login and integrate with ionic cloud services.

**Comment by sagivf** [comment]
@devnetics any news about this. I noticed there is long pull request waiting https://github.com/driftyco/ionic-cloud/pull/46

**Comment by ericb** [comment]
@sagivf This should be coming into a release this week, but i'll have @devnetics send you the details for the beta release if you want to check it out.

**Comment by devnetics** [comment]
Sending to you via Ionic worldwide slack. Thanks!
