### ISSUE TITLE
Tests in fail after upgrade to ionic-cloud 'TypeError: undefined is not an object (evaluating 'this.config.settings.logger')

### ISSUE THREAD

**Issue by coderroggie** [driftyco/ionic-cloud#40]
After upgrading to version 2.0 of the Ionic CLI and moving to ionic-cloud, my jasmine tests run in phantomJS and Chrome fail due to the following error message:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'this.config.settings.logger')
  at www/lib/ionic.cloud.js:1206
```

I've narrowed down the issue to when i add ionic.cloud.js into karma.conf.js file as a source.  The project is an Ionic 1 project.  Beginning to think that I shouldn't have upgraded to version 2 of the CLI in the first place and gone down this road...

Am I missing something some setup here or is this a bug?

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.4 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3.1 Build version 7D1014 

```

**Comment by dwieeb** [comment]
There were _a lot_ of changes made, I apologize I missed this. This was just an order-of-operations thing. If the logger is used before the config is registered, it tries to access a property on an undefined thing. TypeScript 2 would've caught this. 😆 

If you update your library to the latest, it should be resolved. Let me know if there are any other issues.

**Comment by coderroggie** [comment]
That did the trick, thanks :)

**Comment by RickMeijer** [comment]
I got the same type of error after migrating to Ionic Cloud and running a test.
For me it's the config.settings.core that called on line 17922 that is giving the error. After inspecting it doesn't seem there is a config.settings at this point in the code.
The config looks like this:
```
Config {
    urls: {
        api: 'https://api.ionic.io',
        web: 'https://web.ionic.io'
    }
}
```
It's quite annoying to have the test randomly fail, and not being able to do anything about it.
