### ISSUE TITLE
Package error for android build: "A problem occurred configuring root project 'android'."

### ISSUE THREAD

**Issue by jarodms6** [driftyco/ionic-cloud#41]
You have been opted out of telemetry. To change this, run: cordova telemetry on.
ANDROID_HOME=/usr/local/src/android-sdk-linux
JAVA_HOME=/usr/lib/jvm/java-8-oracle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-ads:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-ads/
         file:/home/package/workspace/apps-fed6e0ae-302/cordova/platforms/android/libs/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.873 secs
Error: 
Error code 1 for command: /home/package/workspace/apps-fed6e0ae-302/cordova/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/package/workspace/apps-fed6e0ae-302/cordova/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by dwieeb** [comment]
Odd... The Google Play Services are installed and up to date.

**Comment by jarodms6** [comment]
the last Android build I did was 8/24 (that was successful) and I haven't changed anything with package.json or config.xml

**Comment by dwieeb** [comment]
Yeah, I switched servers. I was tired of the limited resources. Try again? Sorry about that.

**Comment by jarodms6** [comment]
Android build worked. Thanks!

**Comment by xkeerthivasan** [comment]
add to body class: platform-android

ANDROID_HOME=/home/dev5/Android/Sdk

JAVA_HOME=/usr/lib/java/jdk1.8.0_111

Subproject Path: CordovaLib


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 24].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 1.097 secs

Error: /home/dev5/Music/myIonicApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 24].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Higgz1** [comment]
In my experience the solution was to remove or delete the android platform component of the ionic app and to re-install the using the cmd cordova prompt. Hope this helps :-)
