### ISSUE TITLE
availability through bower

### ISSUE THREAD

**Issue by gruppjo** [driftyco/ionic-cloud#43]
Will you provide `ionic-cloud` through bower at some point? Since `ionic-cloud` explicitly supports angular 1 and a lot of angular1/ionic1 apps rely on bower for managing dependencies, I think it would make a lot of sense.

**Comment by ericb** [comment]
@gruppjo We may revisit this in the future, but it's not likely. We do not currently have any plans to support the Cloud client via bower.

**Comment by sdemurjian** [comment]
I would like it to be available through bower as well.
