### ISSUE TITLE
Facebook social login only relaying a bare minimum of values

### ISSUE THREAD

**Issue by jaspervanveghel** [driftyco/ionic-cloud#45]
Following issue #20, which is awesome to have, it would be preferable to have more of the Core fields which should be returned by the Facebook API and available to the Ionic backend. For the particular app that I'm working on now, first_name and last_name would be helpful; we want to display profile pages for users where we refer to them by their first names. Splitting the full_name isn't really reliable for this as some users have two first names, and for others the first/last names in full_name are in reverse order. There are also several other Core fields which I could imagine might be useful to some.

**Comment by devnetics** [comment]
Hey @jaspervanveghel, we actually provide the full facebook response object in the `raw_data` field that gets returned to you. If you are using the cloud client, it would just be `this.user.social.facebook.data.raw_data.PROPERTY_YOU_WANT`, we just provide the most basic details inside of that `data` object for convenience. Check out http://docs.ionic.io/services/users/facebook-auth.html#data for more details there. 

Additionally, I'll add the first_name and last_name properties to our required data scope that gets sent to Facebook, to make sure they get added to that raw_data object (along with the base `name` property that they send by default).

**Comment by devnetics** [comment]
p.s. @jaspervanveghel The change is now live, you should be able to receive `first_name` and `last_name` inside of the `raw_data` attribute in our response object. If you are using the cloud client then you could do...
``` typescript
// Assign to a variable for DRY
const raw = this.user.social.facebook.data.raw_data;
const first = raw.first_name;
const last = raw.last_name;
```

**Comment by jaspervanveghel** [comment]
Very cool. Thank you for the super fast response :)
