### ISSUE TITLE
Push.register() has wrong return signature

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-cloud#48]
Both the documentation and TypeScript intellisense states that `Push.register()` returns a `Promise<PushToken>` but the actually returned data is (at least on ios): 

```
{
  token: string,
  registered: boolean
}
```

While the definition of`PushToken` is: 

```
{
      app_id: string,
      invalidated: date-time,
      token: string,
      created: date-time,
      valid: boolean,
      id: string,
      type: string
}
``` 

Push.saveToken() returns `Promise<PushToken>` as it's stated.

This is an easy fix, but I don't know if you want to introduce a new type for this, or just return with a explicit object signature like `Promise<{ token: string, registered: boolean }>`

**Comment by dwieeb** [comment]
All up to date? 0.9.0? Where are you getting that definition? 

Here's the definition of `PushToken` in 0.9.0: https://github.com/driftyco/ionic-cloud/blob/0.9.0/src/definitions.ts#L1129-L1155

**Comment by NoNameProvided** [comment]
I am using @ionic/cloud-angular@0.4.0 which uses @ionic/cloud@0.9.0. 

Ahh sorry, yeah I took that definition from the http endpoint. But still the `Push.register()` method returns only a `{ token: string, registered: boolean }` object on ios devices, which is definitely not a `PushToken` object. After that the `saveToken()` function returns a valid `PushToken` object, but not the `register()` function.

```ts
this.push.register()
  .then( (token: any) => { // Note this stated as a PushToken but its not, its { token: string, registered: boolean }
    this.push.saveToken(token).then((token: PushToken) => {
    // I do stuff here
  });  
}, (error: any) => { console.error('[PushService] Cannot register push token.') } )
```

![screen shot 2016-09-15 at 8 54 47 pm](https://cloud.githubusercontent.com/assets/4706265/18563120/bc831dd6-7b86-11e6-87d3-335fb58cbd90.png)

**Comment by dwieeb** [comment]
Most of the properties on `PushToken` are optional. We only know `id` and `type` once `saveToken()` is called. `registered` and `saved` can be `undefined` (falsy), but perhaps they should just be required and defaulted to `false` (doing this now).

`{ token: string, registered: boolean }` _does_ adhere to the `PushToken` interface, it's just that some properties aren't filled in until `saveToken()` resolves.

**Comment by dwieeb** [comment]
Honestly, `saveToken()` should be called for you when `register()` is called. I foresee this being a change I make.

**Comment by NoNameProvided** [comment]
Yeah I missed that `id` is optional. Anyway I find this kind of confusing, `id` something devs expect to be mandatory. I would suggest to have a different type for the "bare" token object. So devs can see the difference.

> Honestly, `saveToken()` should be called for you when `register()` is called. I foresee this being a change I make.

Yes, this is a great idea! And it makes introducing a new type for the "bare" tokens unnecessary. 

I can do a PR for this tomorrow or on the weekend.

**Comment by NoNameProvided** [comment]
Thinking of a signature like `register(save: boolean = true)`. So if it's not intended it can be disabled.

**Comment by dwieeb** [comment]
I think it's confusing, too! `saveToken()` should be called for you with `register()`. 😄 

A PR would be excellent. I am out of town for a few weeks starting tomorrow and I'm not sure if a release of the Cloud Client will be made any time soon, FYI.

`save` would be an option. As a convention I've been having options be objects described by interfaces. See the signature of `saveToken()` and `PushSaveTokenOptions`. It's just future proofing for when we want to include more options.

**Comment by NoNameProvided** [comment]
> Something like `register(options?: PushRegisterOptions)` ?

Sounds good, will do it this way. 

>  I am out of town for a few weeks starting tomorrow and I'm not sure if a release of the Cloud Client will be made any time soon, FYI.

No problem, I can use my fork in the meantime.

**Comment by dwieeb** [comment]
@NoNameProvided You may want to pull in the commits I made these past few minutes. I updated the `CONTRIBUTING.md` with the latest development info. Let me know if you have any questions.

Closing this issue--looking forward to your PR.
