### ISSUE TITLE
Login with facebook bad signature for signed_request

### ISSUE THREAD

**Issue by charyorde** [driftyco/ionic-cloud#49]
```
{
   "error": {
      "message": "Bad signature",
      "type": "OAuthException",
      "code": 1,
      "fbtrace_id": "Ecdf72tE+/g"
   }
}
```
Is ionic signing the facebook token before it is returned back?

This is what I'm expecting when I type this in the browser, https://graph.facebook.com/me?access_token=[token gotten from ionic cloud login with facebook service]
```
{
   "name": "Open Graph Test User",
   "id": "xxx"
}
```

#### Platform info
```
Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 
```

**Comment by devnetics** [comment]
Hey @charyorde what exactly are you trying to do? We currently don't return a Facebook access_token as part of our Oauth integration.

We are currently working on adding FB Native login, integrated with our cloud client, which you can track here: https://github.com/driftyco/ionic-cloud/milestone/2

With that, we will be adding access to the facebook_access token. Since it will be requested by the client (user's native device), it will not need to be signed by our server.

If you just need the basic user details, check out this page: http://docs.ionic.io/services/auth/facebook-auth.html#data

**Comment by charyorde** [comment]
> We currently don't return a Facebook access_token as part of our Oauth integration.
`$ionicAuth.login('facebook').then(function(fbprofile) {` 
fbprofile contains access_token returned from Facebook. When I hit the server with the endpoint `https://graph.facebook.com/me?access_token=[token gotten from ionic cloud login with facebook service]`, I get this:
```
{
   "error": {
      "message": "Bad signature",
      "type": "OAuthException",
      "code": 1,
      "fbtrace_id": "Ecdf72tE+/g"
   }
}
```
Can you explain this?

**Comment by ryanrolds** [comment]
What he is saying is that token is not a FB OAuth token. If you want details like name and email, check the `User.social.facebook`.

**Comment by devnetics** [comment]
Ryan is correct, the token we return is not a FB authentication token, but is in fact a token for your user's access to our api (that allows them to access their user data). 

Currently, a successful login will come back as:
```
{ 
  'signup': true,
  'token': 'YOUR_TOKEN_FOR_IONIC_USER_API'
}
```

Let me know if you have any other questions. Closing.

**Comment by nickgraz** [comment]
@devnetics Are you planning on making the FB auth token available through the service? I want to use the Ionic Cloud API but I also need the FB auth token to generate a long-life token for the client to make Facebook Graph API requests. Is there a way to pull the FB auth token out of the $ionicFacebookAuth service after logging in?

**Comment by enzonotario** [comment]
Hi people! Anyone knows how to get an access token using the native facebook login?

If I use cordova-plugin-facebook4 I get an access token so I can get an offline access from my API, but the user that logins throw cordova-plugin-facebook4 doesn't login in Ionic Auth, so I can't use Ionic Push...
