### ISSUE TITLE
Push unregister fails in browser

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-cloud#5]
Calling unregister in a browser throws an error, whereas register just fails silently. A silent fail (maybe with a `console.log` saying the plugin is unavailable) is preferable, to support testing in a browser.

The iOS emulator fails with the same error, as it does not support push.

```Cannot read property 'token' of null at Push.unregister (push.js:168)```

**Comment by dwieeb** [comment]
Thanks @Manduro. I've fixed the problem. `unregister` returns a promise, so it should never have failed in that manner.
