### ISSUE TITLE
Bug or bad karma?

### ISSUE THREAD

**Issue by FrancescoMussi** [driftyco/ionic-cloud#50]
Hello guys.
Sorry to bother.

Yesterday i was testing the Ionic push notification on both ios and android - with production certificate (all properly setup).

It wasn't working. I wasn't receiving any notification.

The Send push - from inside ionic.io dashboard - was working. I was receiving successfully the notifications on both ios and android.

But the cURL request wasn't working at all, both through my API or through Postman.

I had also opened a SO question:

https://stackoverflow.com/questions/39575790/ionic-push-notification-not-receiving-in-ios

But today magically everything works fine.. 
Without any change in the code whatsoever..

Do you know what could be the reason?
There has been some update in ionic cloud or was just an unlucky day yesterday?

**Comment by ericb** [comment]
@FrancescoMussi You were just unlucky. I introduced a bug to a system that push happens to use for 1 thing (facepalm) which caused some (but not all) pushes to fail. We've since pushed a fix that addressed the new bug and everything is in proper order. 

Cheers! :beers:

**Comment by FrancescoMussi** [comment]
Okay thanks! I was starting to doubt my whole life!
