### ISSUE TITLE
Handle a notifications - Push not emitting inside my App

### ISSUE THREAD

**Issue by RonSB** [driftyco/ionic-cloud#51]
Hi,
My app was Ionic version 1 and the notifications worked well, I followed all the [migration ](http://docs.ionic.io/migration.html) steps, and it works only when the app is closed/background.

My app is Ionic 1, I updated to the latest CLI 2.0.0, delete all references to the ionic-platform-web-client.

I place the listener to the 'cloud:push:notification'

 ```
$scope.$on('cloud:push:notification', function(event, data) {
    var msg = data.message;
    alert(msg.title + ': ' + msg.text);
 });
```

Use this different method to handle the notification on my controller, or where I have to put this method ?:

```
$ionicEventEmitter.on('push:notification', function(data) {
     console.log(data.message);
});

```
I removed the ionic cloud and the phonegap-plugin-push and I installed them again (ionic cloud 0.9.0).

After trying all this my problem persists, does anyone have any solution?

**Comment by koenoe** [comment]
For me the `cloud:push:notification` is also not working. It's not firing.

**Comment by ericb** [comment]
Are you correctly using $scope for the context of your app / code placement? You mentioned it works when the app is in the background/closed, but does that just mean that the notification is displayed in the notification area? If you click the notification when the app is closed, does the cloud:push:notification event fire then?

**Comment by koenoe** [comment]
I'm receiving the actual push notification. I've put some logging in my ionic-cloud-bundle file now and I discovered there's also an event `cloud:push:register`. If I listen to this one for example I successfully receive it. It doesn't matter whether I close the app and click the notification or I leave the app open. In both cases I'm not receiving the `cloud:push:notification` event. I'm using Ionic 1.3 and Ionic Cloud 0.10.0.

I initialise Ionic Cloud as suggested in my app config block. I listen to the events in my app run block:
```
$rootScope.$on('cloud:push:register', onDeviceTokenRegistered); // works
$rootScope.$on('cloud:push:notification', onPushNotification); // doesn't work
```

**Comment by ericb** [comment]
@koenoe Both events fire in the same way, and are registered internally at the same time. What happens if you try and listen for events directly from the Push Plugin? I haven't run this code directly, but it should be something like:

```javascript
$ionicPush.plugin.on('notification', function(data) { console.log(data); });
```

You can see [the relevant callback registration](https://github.com/driftyco/ionic-cloud/blob/master/src/push/push.ts#L295-L322) in the cloud client codebase if it helps.

Also, are you using the latest version of both the cloud client and push plugin?

**Comment by koenoe** [comment]
@ericb Thanks for the suggestion. I've tried it, but no luck.
I'm using ionic-cloud 0.10.0 and the phonegap-plugin-push 1.8.2

**Comment by ericb** [comment]
@koenoe Is an error thrown, or does it just not do anything? If you do the same thing but use 'registration'  as the event type, does it then log something? If so, this would point at something going wrong on the plugin side (perhaps an older version or misconfiguration, etc)

**Comment by koenoe** [comment]
@ericb I literally have no idea what went wrong. But after I started this morning again and had to reboot my MacBook and reopened Xcode, it all of a sudden works. Didn't change anything in the code! I see the 'payload' is in a property 'additionalData', so I'm going to change that now. Thanks, but I think this issue can be closed. Unless @RonSB still have problems?

**Comment by ericb** [comment]
@koenoe Odd. Maybe something wasn't properly picking up the latest versions of the plugin or cloud client? Either way, glad to hear it's fixed up for you. 

Cheers 🍻

**Comment by RonSB** [comment]
Hi @ericb 

Sorry for delay...

I'm using the last version for ionic/cloud (0.10.0) and the problem persisted in android, I will test in IOS.

Regards.

**Comment by RonSB** [comment]
Hi @ericb

I'm using the last ionic/cloud@0.10.0
I wrote this code in App.js file and I tested:

```
 $rootScope.$on('cloud:push:notification', function (event, data) {
        alert('app $rootScope -- cloud:push:notification ' + JSON.stringify(data));
  });
```

and now it fired but only when the app is closed/background.
I don't know if I have to write this code in other place?

**Comment by Lestt** [comment]
Hi all,

I'am using the lastest _ionic/cloud@0.14.1_, _phonegap-plugin-push@~1.8.4_ (because i am using _cordova-android@5.2.2_), _ionic@1.3.0_.

I can receive notification on Android (app in foreground or background), but still the same probleme as here, the **cloud:push:notification** event is not fired at all.
I put this code in my app.js, inside the $ionicPlatform.ready function (which is inside the run function):

```
.run(function($ionicPlatform, $rootScope) {
    $ionicPlatform.ready(function() {
        $rootScope.$on('cloud:push:notification', function(event, data) {
            alert('app $rootScope -- cloud:push:notification ' + JSON.stringify(data));
        });
    });
});
```

Did i miss something ? Thanks for the help !

**Comment by ericb** [comment]
Is anyone able to provide a sample project we can try and replicate against?

**Comment by Lestt** [comment]
First, thank you @ericb for your work.
I found why I didn't get the event. The thing is i am testing my app with livereload. I initialized the push plugin only when the user log in. So in my case, when i use livereload, all the data stored in localStorage (concerning my app or push notifications) are present, but i don't call the code to initialize it between 2 livereload sessions. Then no event is fired.
I re-tested and each time i saved my code and livereload reloaded the app, i logged out and logged into my app, and the event is fired as expected.
I don't know if this should be mentioned somewhere in the doc, and if this behavior seems normal for you.

Thanks for your time ... and Merry Christmas and happy new year!

**Comment by gagansaini2** [comment]
@Lestt @ericb 
In my App, device is registered with ionicPush when a user log in into the app, so when a notification came $rootScope.$on('cloud:push:notification') triggers as expected,but when i close the app and restart it again $rootScope.$on('cloud:push:notification') function stops triggering(but i receives the pushes in my notification shade). So, to trigger push i have to log out ang log in to the app again without closing it.

**Comment by zmaximo1990** [comment]
+1

**Comment by priyankmaniar** [comment]
I can confirm this issue too. $rootScope.$on('cloud:push:notification') doesn't always work.

**Comment by zmaximo1990** [comment]
@priyankmaniar you have to register push notification always the app init. It works for me.

**Comment by priyankmaniar** [comment]
@zmaximo1990 Thanks so much for responding. Do you mean  $ionicCloudProvider.init? I have it in app.js in the .config block.

Here's how it looks.

`.config(function ($ionicCloudProvider) {

        $ionicCloudProvider.init({
            "core": {
                "app_id": "XXX"
            },
            "push": {
                "sender_id": "XXX",
                "pluginConfig": {
                    "ios": {
                        "badge": true,
                        "sound": true
                    },
                    "android": {
                        "iconColor": "XXX",
                        "icon": "icon"
                    }
                }
            }
        });

})`

**Comment by zmaximo1990** [comment]
@priyankmaniar I mean that you have to bind 'cloud:push:notification' event always that app run. In my run bock bind this event on $rootScope if user has logged in.

I hope it help you.
