### ISSUE TITLE
Ionic Package - Adding Custom file into iOS workspace for cordova plugin

### ISSUE THREAD

**Issue by dmastag** [driftyco/ionic-cloud#54]
**Short description of the problem:**

I am testing the implementation of this plugin for firebase notifications, which works perfectly for android
https://github.com/guyromb/cordova-plugin-fcm-plus

Since I don't have a Mac, I am relying on the power of Ionic Package to create all my .ipa files. But one of the requirements of this plugin is _to put the GoogleService-Info.plist inside the platform folder_
And with Ionic Package am getting this error over here

```
Fetching plugin "https://github.com/guyromb/cordova-plugin-fcm-plus" via git clone
Repository "https://github.com/guyromb/cordova-plugin-fcm-plus" checked out to git ref "master".
Installing "cordova-plugin-fcm" for ios
Failed to install 'cordova-plugin-fcm':CordovaError: Uh oh!
cannot find "/Users/package/workspace/apps-b86d9bac-25/cordova/GoogleService-Info.plist" ios <resource-file>
    at handlers.resource-file.install (/Users/package/workspace/apps-b86d9bac-25/cordova/platforms/ios/cordova/lib/plugman/pluginHandlers.js:53:48)
    at Object.ActionStack.process (/Users/package/workspace/apps-b86d9bac-25/cordova/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.addPlugin (/Users/package/workspace/apps-b86d9bac-25/cordova/platforms/ios/cordova/lib/plugman/Plugman.js:82:20)
    at Api.addPlugin (/Users/package/workspace/apps-b86d9bac-25/cordova/platforms/ios/cordova/Api.js:187:53)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:605:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:403:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
Error: Uh oh!
cannot find "/Users/package/workspace/apps-b86d9bac-25/cordova/GoogleService-Info.plist" ios <resource-file>
```

**What behavior are you expecting?**

Being able to put the GoogleService-Info.plist file somewhere so it is picked up during the ionic package build process

**Which Ionic Cloud Service?**
Ionic Package

**System information**
Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Distributor ID: LinuxMint Description: Linux Mint 17.3 Rosa
Node Version: v6.6.0

**Comment by ericb** [comment]
Hi @dmastag. This is because we only package a few known files for the build process. Are you tied to using the plugin you've linked? We offer a push notification service and use the `phonegap-plugin-push` plugin which works with Package.

**Comment by dmastag** [comment]
Hi @ericb ,
Yes, tried using the plugin that I linked with no success. The phonegap-plugin-push one is not tested for FCM yet, but according to this https://github.com/phonegap/phonegap-plugin-push/issues/929 version 2 can be tested for it.

Let me try to play around with it and see what happens.

**Comment by ddomonkos** [comment]
Hi guys,
so is there no way how to place the .plist file in the (platform's) project root folder? I would like to use the FCM plugin and I don't have a Mac either. I tried to solve it via a 'before_build' hook but it wasn't being fired (which is logical, after all).

**Comment by ericb** [comment]
@ddomonkos Check out the [package-hooks](https://github.com/driftyco/ionic-package-hooks) repo. You can write your own hook and submit to the repo (as long as it's generic and generally safe we will likely bring it in). [This hook](https://github.com/driftyco/ionic-package-hooks/blob/master/ios9_allow_http.sh) is a likely a good starting point for what you want to do.

**Comment by ddomonkos** [comment]
Thank you @ericb, that would have certainly worked. But in the meantime I managed to solve it with the help of this plugin https://github.com/stetro/cordova-plugin-fcm-config; I forked it and created my own private repo, where I put the .plist file. Your help is much appreciated though.

**Comment by ericb** [comment]
No problem, cheers 🍻
