### ISSUE TITLE
Store Facebook auth Push token?

### ISSUE THREAD

**Issue by atlance01** [driftyco/ionic-cloud#58]
Hey everyone,

I've spent the last couple days trying to fix this issue. I've got Facebook auth up and running in my app. The users appear as they should in the IO dashboard.

Then, I've got $ionicPush.register() called on index.html which then saves the token using the bit of code from the docs. But it doesn't ever seem to save the token or possibly there was never one to begin with.

Here's a bit of my code that is triggered by a button press:
```
`$scope.registerPush = function () {
        console.log('called registerPush');
        $ionicPush.register().then(function(t) {
                console.log('called register');
                $ionicPush.saveToken(t);
                $ionicUser.save();
            }).then(function(t) {
                console.log('Token saved:', t.token);
        });

    };`
```

Anyone have any ideas what could be happening? Did I miss something obvious?

**Comment by dwieeb** [comment]
I'm not sure what you're expecting to happen or what you want to happen. `$ionicPush.saveToken()` saves the _push_ token. The _auth_ token (Facebook's user access token), which is probably what you want, is not saved on the user currently, but there is an ongoing PR that will have this: https://github.com/driftyco/ionic-cloud/pull/46

**Comment by atlance01** [comment]
I assumed that once I've auth'd with Facebook, that I'd be able to send out push notifications by associating the Facebook user with their push token?

![screen shot 2016-09-28 at 4 41 56 pm 2](https://cloud.githubusercontent.com/assets/13652692/18931582/c9f7fb9e-859a-11e6-9f7f-bf2f53792563.png)

How can I store a push token thats associated with a facebook user? I assumed that would show up in the screen above.

Also I never see this log show up in my console:`console.log('Token saved:', t.token);`

**Comment by dwieeb** [comment]
Ah, I see. Nothing is really standing out as to why it shouldn't be working for you. 

Both `register()` and `saveToken()` return promises. Since you're not returning a promise in the `then()` handler of `register()`, the next `then()` won't ever be called. So call `$ionicUser.save()` in the next `then()` and _return_ the promise returned by `$ionicPush.saveToken(t);`. These calls aren't synchronous. Also, make sure `$ionicAuth.login()` is called before `$ionicPush.register()`.

**Comment by atlance01** [comment]
First off, thank you for giving me such a thoughtful replies. 

I tried your suggestions and I'm seeing any progress on my end. Myself and a fellow co-wowker spent some time console.logging various parts of the ionic.cloud.js files - specifically around the registration function and have found that the registration function is never actually executing on my machine.

In my console, _t_ always has the blockRegistration value of _true_, although I have an authToken string value and _Registered_ equals _true_.

Does this help narrow down the issue at all?

**Comment by atlance01** [comment]
@dwieeb This worked!!! Thanks a million-billion. Ionic.io dashboard is the jammm.
