### ISSUE TITLE
How to use with Ionic RC.0? 

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-cloud#59]
In Ionic RC.0 the `provideCloud(CLOUD_SETTINGS)` cannot be added to the providers so the initialization of `Push` fails.

**Comment by dwieeb** [comment]
@NoNameProvided I am currently in the process of cutting a release for the client as we speak. I will update this issue when the release is made!

**Comment by dwieeb** [comment]
@NoNameProvided Please try updating the Cloud Client. The new configuration docs are here: http://docs.ionic.io/setup.html#configuration (switch to Ionic 2 docs if you have to).

Let me know if you have any issues!

**Comment by NoNameProvided** [comment]
Thanks!

**Comment by NoNameProvided** [comment]
Hmm it seems, it doesn't works for me. Adding the `CloudModule.forRoot(CLOUD_SETTINGS)` line will cause still the same ngc error:

```
ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in... 
```

Otherwise my app works well. So if I add this line, ngc dies, if I remove it everything goes smoothly.

Note: I am upgrading an app, not creating one from scratch.

**Comment by dwieeb** [comment]
@NoNameProvided looking

**Comment by dwieeb** [comment]
Okay, looks like more is needed to prep the cloud client for ngc. Despite my best efforts, I'm still getting that same error. I may need to look at this tomorrow, instead.

**Comment by dwieeb** [comment]
@NoNameProvided Please update and try again!

**Comment by NoNameProvided** [comment]
Thanks, it works now!
