### ISSUE TITLE
Handle a notification

### ISSUE THREAD

**Issue by eweap** [driftyco/ionic-cloud#6]
Hello, what is the best way to handle a notification with 'ionic-cloud' ? Before we used to pass a `onNotification` method during `$ionicPush.init()` but know that only `debug` and `pluginConfig` is available i don't know how to handle the incoming notifications.

Thanks

**Comment by dwieeb** [comment]
A migration guide is forthcoming, but to answer your question, there is now an `$ionicEventEmitter` that you can subscribe to. 

```javascript
$ionicEventEmitter.on('push:notification', function(notification) {
    // handle notification here
});
```

**Comment by eweap** [comment]
Thanks for your quick answer @dwieeb !

**Comment by dwieeb** [comment]
@eweap We now have official docs for handling push notifications: http://docs.ionic.io/services/push/#handling-notifications
