### ISSUE TITLE
PWA Login for Social Providers

### ISSUE THREAD

**Issue by mrmoses** [driftyco/ionic-cloud#61]
Login with social providers from website/PWA does not seem to work.

The first issue seems to be the InAppBrowser requirement. A pure browser implementation can do things like window.open, so the InAppBrowser plugin shouldn't be necessary. I tried a quick workaround by setting `window.cordova.InAppBrowser = window` so that the call to `window.cordova.InAppBrowser.open()` would just use `window.open()` and that seemed to open the popup window just fine.

The second issue I found is that after the authorization happens in the popup window there is a redirect to an auth.ionic.io URL which contains the token, but auth.ionic.io is does not seem to be a working domain. Looks like InAppBrowser plugin catches this redirect and parses out the token, but a pure browser (I'm using Chrome) doesn't trigger a 'loadstart' event, so the user just gets an error screen in the popup window (DNS address could not be found). Not sure if there's a more standard event to handle.

I'd really like to have this functionality, so I could work on it and provide a PR, but would like to know if this is something that would be accepted, and what kind of direction to take with it.

Since PWAs are a first-class citizen, should this be included in the Native Login for Social Providers milestone?

**Comment by ericb** [comment]
You're definitely not the first person with this issue and there are some other areas where this same scenario fails so I'd like to address this for everyone within the next week or two. I've got some notes already written up in other issues posted previously (sorry I don't have time to find them right now), but they definitely address what you've written up here.

I'm keeping this open for now until I have more time to link this up with the other posted issues.

👍

**Comment by ericb** [comment]
Here is the [issue thread](https://github.com/driftyco/ionic-cloud/issues/53) I mentioned earlier @mrmoses

I'm closing this issue now so please follow along on issue #53

**Comment by theteedog** [comment]
Is there an ETA on when Ionic Cloud Auth will support social providers for PWA?  I'm currently handling auth myself but would prefer to use Ionic Cloud.
