### ISSUE TITLE
ionic package build ios with ionic 2 rc0 results with default cordova app

### ISSUE THREAD

**Issue by comfortme** [driftyco/ionic-cloud#62]
hi!
after i updated my project to rc0, i used ionic package build ios and resulting app was default cordova device ready app that looked like this. this doesn't happen with package build android.

![image](https://cloud.githubusercontent.com/assets/18467824/19016683/50f7cc82-882a-11e6-8ea2-8fc36560a489.png)

**Comment by comfortme** [comment]
i can say that it's not related to rc0 it happens to my beta11 app too.
it was working fine before i updated ionic cli maybe that?

**Comment by omhybrid** [comment]
yes i have same problem

**Comment by omhybrid** [comment]
@comfortme did you solve this? plaese help

**Comment by comfortme** [comment]
not kind of a problem that we can solve.
there are issues and forum posts about it here

issues:
driftyco/ionic-cloud-issues#197
forum post:
https://forum.ionicframework.com/t/ionic-package-ios-build-fails-development-team-required/65033/15

**Comment by ericb** [comment]
Hey guys, 

There have been a number of different issues all cropping up with the timing of all these new releases (ionic 2 update, ionic cli update, iOS 10, cloud client updates, etc). But from the original post I think this was simply the result of how dependency injection changed with Angular 2 (which subsequently changed in Ionic 2 RC0).

We've updated the cloud client to reflect these changes, so if you have updated your Ionic 2 version, you should also update the cloud client.

iOS 10 issues with package will be resolved shortly after the next cordova release (I believe this is coming soon).

Hope that gives you guys a little more information, and let me know if you're still encountering issues 👍

**Comment by comfortme** [comment]
hi ericb
yes it is working again! thank you.
