### ISSUE TITLE
DeployDownloadOptions

### ISSUE THREAD

**Issue by meeximum** [driftyco/ionic-cloud#64]
Hi,

ist there an example how I can get progress information during downloading a package?

regards
Meex

**Comment by ericb** [comment]
We need to show examples of this in the documentation, but it's just done as a progress callback of `download` and `extract`:

```javascript
$ionicDeploy.download({
  'onProgress': function(progress) { 
    console.log(progress);
  }
});
```

**Comment by meeximum** [comment]
thx a lot!
