### ISSUE TITLE
Facebook Login Unprocessable Entity

### ISSUE THREAD

**Issue by SimoKorp** [driftyco/ionic-cloud#65]
https://forum.ionicframework.com/t/ionic-auth-signup-unprocessable-entity/60417/6

As discussed there the facebook auth suddenly doesn't work in my app anymore. LinkedIn and GitHub on the other hand work just fine eventhough the code is exactly the same excluding the auth provider name: 

       this.platform.ready().then(() => {
             this.auth.login('facebook').then((success) => {
                      this.navCtrl.push(ModeSelectPage);
              }, (error) => {
                     console.log("error: " + error );
              });
        });

The error reads as follows: error: Error: UNPROCESSABLE ENTITY

**Comment by ericb** [comment]
@SimoKorp I've just pushed a fix that should resolve this. Check out https://github.com/driftyco/ionic-cloud/issues/67 for more info.
