### ISSUE TITLE
422 Unprocessable Entity error when logging in with Google or Facebook

### ISSUE THREAD

**Issue by jbasinger** [driftyco/ionic-cloud#67]
I'm calling $ionicAuth.login('facebook') and getting an error immediately with this response:

`{"meta": {"version": "2.0.0-beta.0", "status": 422, "request_id": "d6ecff9a-4c1a-474a-9e99-d17582282f47"}, "error": {"message": "An error occurred while validating the request parameters.", "type": "UnprocessableEntity", "link": null, "details": [{"error_type": "required", "errors": ["Missing data for required field."], "parameter": "flow"}]}}`

The request was a POST to https://api.ionic.io/auth/login/facebook

Here is the request payload:

`{app_id: "b439877c", callback: "http://192.168.10.132:8100/#/login", data: {}}`

I'm not sure what the "flow" parameter is, or why it is missing, or if that is even the field that is missing. I'm not sure if this matters or not, but I'm using the 1.3 version of Ionic and the version in the response says 2.0. Any ideas? This was working fine yesterday =(

**Comment by ericb** [comment]
@jbasinger We recently pushed some updates for upcoming auth features which inadvertently affected current setups, but I've pushed an update that should have fixed things up for you. Can you try again?

**Comment by devnetics** [comment]
Tested and confirmed this is fixed. Closing for now. Update here @jbasinger if you have any issues.

**Comment by jbasinger** [comment]
Worked again for me as well. Thanks for the fast response guys! You rock.
