### ISSUE TITLE
Push notifications from development profile do not work

### ISSUE THREAD

**Issue by KixS** [driftyco/ionic-cloud#68]
Hi,

I have configured two profiles to use for push notifications. A development profile and a production profile.
I am doing tests on Android to update to the new FCM system. I have as well two databases on firebase, one for development and one for production. So I have two sender-ids.

When I build my app to test it using the development sender-id, all notifications that I send with the development profile return GCM_INVALID_REGISTRATION. Howerver when I send notifications just by changing the profile to the production one, my app that has been built with the development sender-id (i am using phonegap-plugin-push), instantly receives the notification.

Is this a normal behavior ?

**Comment by ericb** [comment]
You need to make sure to update your app to use the correct sender id for each environment. A token must then be registered using that sender id, which can then only be sent using that sender id. 

cc @Fuiste

**Comment by Fuiste** [comment]
Yeah, my guess is that you're registering tokens for the production sender ID inadvertently, and as such API requests with the development server key are invalid.

It's also possible that there is an issue with the development server key/id you created, requiring them to be regenerated (this is highly unlikely, though).

**Comment by KixS** [comment]
Thank you both for your answer!

I think the issue is coming from a misconfiguration of ionic-cloud from when I did the migration from the web-platform but when I try to reconfigure, I keep bumping into other issues.

So as you said, the registration is certainly sending the wrong id.
