### ISSUE TITLE
Cordova.js not found after update using Deploy

### ISSUE THREAD

**Issue by durasj** [driftyco/ionic-cloud#70]
Hello,

I've been using older web client successfully. Recently I switched to the new cloud client and although update seems to be successful, app won't be able to load cordova.js (see console output below) which will lead to user being stuck at splashscreen after restart. I tried building app in Ionic Package, Sierra/XCode 8 on both macbook and in virtual machine.

![ionic deploy update cordova js fail](https://cloud.githubusercontent.com/assets/1062898/19270469/7a02abb8-8fc0-11e6-8d6a-384204258940.jpg)

I tried to keep implementation pretty straightforward:

```
        return this.$ionicDeploy.download().then(() => {
            return this.$ionicDeploy.extract().then(() => {
                this.$ionicDeploy.load();
            });
        });
```

I also recently switched to WKWebView (probably before migrating to cloud client) so I'm wondering if that combination could be somehow problematic.

Thank you for any help

**Comment by jay8585** [comment]
Same issue with me...
Somebody help us! I also checked whitelist!!

**Comment by durasj** [comment]
Hi @jay8585,

are you please using WKWebView?

Thanks

**Comment by jay8585** [comment]
Hello @durasj 
Actually I'm not using WKWebView.. ^^

**Comment by ericb** [comment]
If you've updated the cloud client, you'll need to update the deploy plugin as well.

**Comment by jay8585** [comment]
Thanks @ericb 
My ionic-plugin-deploy version was 0.57 but ionic-cloud users should use 0.6.x version.
![image](https://cloud.githubusercontent.com/assets/8064923/19271146/390244b4-8ffe-11e6-8b43-dc795a40756e.png)

@ericb 's solution fixed my problem! Thanks :D

**Comment by ericb** [comment]
Awesome, glad to hear it! Cheers 🍻

**Comment by durasj** [comment]
Fixed the issue.

Strange is that project was recreated in different environments and the plugin was not updated. I also thought `ionic reset` would remove and add all plugins and platforms, which would update them, since there is no trace of version in package.json which is used by ionic state.

Thank you nonetheless

**Comment by durasj** [comment]
Hi @ericb,

I just checked it again, and while the issue with app going down after restart is gone, the issue visible in the screen - which is .load() right after the update - is still there and App won't restart.

This is not as big issue as the problem after the reload, as one can suggest the user to reload the app, but still.

**Comment by durasj** [comment]
For anyone reading this issue, looks like [#99 @ ionic-plugin-deploy](https://github.com/driftyco/ionic-plugin-deploy/issues/99) is the possible problem for now - wkwebview.
