### ISSUE TITLE
Facebook authentication: Invalid state parameter provided

### ISSUE THREAD

**Issue by fetimo** [driftyco/ionic-cloud#71]
Sometimes when using Ionic Auth and signing up with Facebook we see the following error message after users have entered their email and password successfully:

![Facebook error](http://i.imgur.com/MkBdG0Y.png)

Sometimes this happens multiple times in a row, other times it happens once, and often not at all.

The code to initiate `$ionicAuth.login('facebook')` is bound to a button. I did notice that it was possible to tap the button twice so I added a debounce function so the button's click handler is only run once in a 1 second period. Unfortunately we're still seeing it.

We're seeing the issue with Ionic Cloud 0.9.0 and 0.10.0.

**Comment by nicksmithr** [comment]
Having this same issue for Instagram. Did you find a solution?

**Comment by fetimo** [comment]
@nicksmithr We moved to the native Facebook implementation and haven't had an issue since. Sorry!

**Comment by ericb** [comment]
I believe this was directly tied to the same issue @nicksmithr was experiencing and should be fixed up now.
