### ISSUE TITLE
Ionic 1.x - $ionicDeploy.check() is not resolving -- traced up to device.ready event handler not being fired

### ISSUE THREAD

**Issue by jamesvsshark** [driftyco/ionic-cloud#73]
Hello,

I'm facing an issue with $ionicDeploy.check() where the function is not resolving. I am using a real device. I have wrapped it in $ionicPlatform.ready and had it inside of angular1 run block and a controller and no luck.

I did some digging into the Ionic.cloud.js file and it appears the issue that the check function in itself is waiting for the event of "deploy:ready" to do it's thing -- this is not being called.

I can see that the initialization of the Deploy service itself is responsible for emitting this event but that listens for a "device:ready" event which is to be emitted from the device ready listener in the  Cordova.prototype.bootstrap function.

Not sure what is preventing the deviceready to be fired within ionic.cloud.js -- FWIW it's in the $ionicPlatform service the .ready function works and is being called. 

I've updated all of my client libs, added and removed platforms and no luck. Any help would be much appreciated.

**Comment by dwieeb** [comment]
@jamesvsshark I assume you're testing this on a device or an emulator? It sounds like Cordova's `deviceready` event isn't being triggered. Can you verify this theory by doing something simple like this: https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready

**Comment by jamesvsshark** [comment]
Your theory is right. It's not being fired. I added that snippet with a console log inside of run block inside and outside an $ionicPlatform.ready check and inside a controller and there is nothing being logged.

**Comment by dwieeb** [comment]
Is `window.cordova` defined?

**Comment by jamesvsshark** [comment]
No it is `undefined`.

**Comment by jamesvsshark** [comment]
@dwieeb thank you for pointing me in the direction. I found the issue! Someone in my index.html this line was removed    ` <script src="cordova.js"></script>`

After adding cordova.js file back and adjusting CSP policy I am back in action! 

Thank you so much!

**Comment by dwieeb** [comment]
Glad to hear! Cheers 🍻
