### ISSUE TITLE
Push notification service is down?

### ISSUE THREAD

**Issue by asafco4** [driftyco/ionic-cloud#74]
Everything was working great until today, suddenly no push notifications received.

My server shows that I get return code 201 (success) and this is one of the authorization ids I got:
"Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4YTQ5YWFkYS1lMDdjLTRhOWUtOWVjYi02ODA4ZWQ0ZjcwODMifQ.X0EXPOFYwswrx8NicqzLe87E2OiKzx213caBvGNecX8"

Please advise.

PS. there's no official support team for those? Somewhere we can check if service is indeed down?

**Comment by ericb** [comment]
The push service is up and running (any outages will be posted to to our [status page](http://status.ionic.io/)). There has been no downtime today that we are aware of. Have you checked the status of your messages?

**Comment by asafco4** [comment]
Hi Eric, thanks for your reply.

Can you elaborate on what you mean by status messages?
I send the request to send the push and the reply is:

{"statusCode":201,"body":{"data":{"app_id":"486aaf62","uuid":"26c05c71-429b-4d89-8fd3-9aba13111921","created":"2016-10-17T06:15:03.624467+00:00","status":"open","state":"enqueued","config":{"notification":{"ios":{"title":"8","message":"8"},"message":"8","android":{"data":{"title":"8","message":"8"}}},"tokens":["f4cF8AdObQw:APA91bGCyDiRFdRWINZKoTXOIjD0Uu_1ZThF15wVW5X8Uguu-YwqH9Xyjhz4Zo4CCCsNMrXtpjoQ8llUH6-766sjNMXEMU1lH30zJORD19vDzhi5NVUxrANZU_gQ6fu75gxuvq386rIq"],"profile":"winnerzstore"}},"meta":{"version":"2.0.0-beta.0","request_id":"91a41c29-d65c-4ab9-a115-106fe9228629","status":201}},"headers":{"connection":"close","server":"nginx","date":"Mon, 17 Oct 2016 06:15:03 GMT","content-type":"application/json; charset=utf-8","content-length":"605","via":"1.1 vegur, 1.1 vegur","access-control-allow-credentials":"true","access-control-allow-methods":"HEAD,GET,POST,PATCH,PUT,DELETE,OPTIONS","access-control-allow-headers":"DNT,Authorization,X-CSRFToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.ionic.io","port":443,"hostname":"api.ionic.io","hash":null,"search":null,"query":null,"pathname":"/push/notifications","path":"/push/notifications","href":"https://api.ionic.io/push/notifications"},"method":"POST","headers":{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4YTQ5YWFkYS1lMDdjLTRhOWUtOWVjYi02ODA4ZWQ0ZjcwODMifQ.X0EXPOFYwswrx8NicqzLe87E2OiKzx213caBvGNecX8","accept":"application/json","content-length":304}}}

Does that not mean that the push should arrive to the device?

**Comment by asafco4** [comment]
I think I now get what you said... 
Is there a quick & easy way to check the statuses of already sent push notifications?
I remember last time I had some hard times with curl due to special chars like ", ', /, \
Thanks

**Comment by Fuiste** [comment]
@asafco4 there's two main ways to check the status of extant notifications.

First, you can use the `overview` field on the `notifications` endpoint for a simple listing of the number of messages delivered, invalid, error, etc ([docs](http://docs.ionic.io/api/endpoints/push.html#get-notifications)).

Second, you can use the `notifications/<uuid>/messages` endpoint for a more granular view of the messages for a given notification.  This will give you the status, token, and ID for every message in a notification ([docs](http://docs.ionic.io/api/endpoints/push.html#get-notifications-notification_id-messages)).

**Comment by asafco4** [comment]
@Fuiste  / @ericb 

This is my latest notification request:
{
			"state" : "enqueued",
			"app_id" : "********",
			"created" : "2016-10-18T04:09:08.196492+00:00",
			"uuid" : "6a506c5c-e826-4ccd-913e-ece6dda560d9",
			"config" : {
				"tokens" : ["f4cF8AdObQw:APA91bGCyDiRFdRWINZKoTXOIjD0Uu_1ZThF15wVW5X8Uguu-YwqH9Xyjhz4Zo4CCCsNMrXtpjoQ8llUH6-766sjNMXEMU1lH30zJORD19vDzhi5NV**************"],
				"notification" : {
					"message" : "test1",
					"ios" : {
						"message" : "test1",
						"title" : "test1"
					},
					"android" : {
						"data" : {
							"message" : "test1",
							"title" : "test1"
						}
					}
				},
				"profile" : "*********"
			},
			"status" : "locked"
		}

I then ran the API for the message using the uuid and got:
{"data": [], "meta": {"status": 200, "request_id": "ed11612e-2f6b-4506-810c-f690b6da3dba", "version": "2.0.0-beta.0"}}

Can you please explain what's wrong? Should the data item be empty?
I'm telling you, it worked great til yesterday and then something changed.
Did you enforce version 2 or something? My app is in the store already, server was untouched, something was changed on your side for sure ...

**Comment by ericb** [comment]
@asafco4 If you do not see any messages sent, but everything was successful, that means no valid tokens were found, so we did not attempt to create any messages. We're working on being able to show this in the overview section.

If the token itself is actually valid and it's an issue with the profile you're using to send it, you can see an actual error code by re-validating the token (using [this](http://docs.ionic.io/api/endpoints/push.html#patch-tokens-token_id) endpoint) and attempting another send to it.

It will then think the token is valid and attempt to send to it again.

**Comment by Fuiste** [comment]
@asafco4 what @ericb said is correct, however I'd add that you _can_ currently see the number of invalid tokens for a given notification using the `overview` field in the API ([docs](http://docs.ionic.io/api/endpoints/push.html#get-notifications)), or from the dashboard once the notification has been sent.

**Comment by asafco4** [comment]
Thanks guys, I'll tests those suggestions and update.

**Comment by asafco4** [comment]
@ericb , @Fuiste ,, I have some findings:
My problem is with the token, from some reason it's now invalidated.
I was sure that when I create Ionic.push object and call push.register then I get a new token or at least that the current one will be extended, but in reality I keep getting the same invalidated token.
is that wrong assumption?

This is the login code:
if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
		
			// Ionic.io push notifications
			var push = new Ionic.Push({
				"debug": true,
				"onNotification": function(notification) {
					var payload = notification.payload;
					
					if(notification.app.asleep || notification.app.closed) {
						// the app was open, but in the background when the user clicked the notification OR
						// the app was not open when the user clicked the notification						
					}
					else {
						if ($state.current.name == "flash-login" || $state.current.name == "login" || skip.getSkipSession() ||
							$state.current.name == "loggedIn.gift_details" || $state.current.name == "loggedIn.mission_details") {
							console.log("onNotification: ignore the popup"); 
							return;
						} else if ($state.current.name == "loggedIn.auction_details") {
							$state.reload();
						} else {
							console.log("onNotification: ", notification)
							var param = {
								text: notification.text, 
								title: notification._raw.additionalData.data.title ? notification._raw.additionalData.data.title : notification.title
							};
							popups.notificationPopup(param).then(function(){
								$state.reload();
							});
						}
					}
					
				},
				"onRegister": function(data) {
					console.log("onRegister: ", data.token);
				}
			});
			
			var callback = function(token) {
			  console.log('Registered token:', token.token);
			  push.saveToken(token, {'ignore_user': true});		  
			  $rootScope.notificationsToken = token.token;
			  $rootScope.pushObject = push;
			}

			push.register(callback); // End of Ionic.io notifications
		}

The logout code:

				if (ionic.Platform.isAndroid() || ionic.Platform.isIOS()) {
					console.log("logout: Unregister Ionic");
					var push = $rootScope.pushObject;
					push.unregister();
					$window.localStorage.removeItem("refer_link");
				}

Can you please advise?

Thanks!

**Comment by Fuiste** [comment]
@asafco4 couple things.

- `.unregister()` will mark a token as invalid, which is likely the source of your issues.
- If you wish to continue using `unregister`, you can update the validity of tokens using [this](http://docs.ionic.io/api/endpoints/push.html#patch-tokens-token_id) endpoint.

**Comment by asafco4** [comment]
@Fuiste , thanks for your quick reply.

1. Assuming I keep using the unregister, the register should not get me new token?
2. Can I just remove the unregister and it's not gonna cause issues? 
3. If I don't invalidate it, how long that token will remain valid?

**Comment by Fuiste** [comment]
1. Tokens are generated on a per-device, per-app basis, and will rarely id ever change
2. Yes, this should not cause issues, though the token will remain valid and able to receive pushes.  A better method would be to delete the token from the user when the logout.
3. Indefinitely, as far as I know.  I've got a testing app that still receives pushes on a 2 year old token.  That said, you _should_ be calling `register` on each app start to be safe.

**Comment by asafco4** [comment]
Thank you very much!!!

**Comment by Fuiste** [comment]
Glad to help, cheers!
