### ISSUE TITLE
ionic 1 project ios package build succsess fully but it small size before updated cli and in app navigation of all button not working

### ISSUE THREAD

**Issue by omhybrid** [driftyco/ionic-cloud#75]
My Config

Cordova CLI: 6.3.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7
Node Version: v4.5.0

before updated ipa file create around  6.0 mb but after updated ionic cli its create 4.0 mb and app is open but not working navigation of button

android build is working good.

**Comment by ericb** [comment]
What is your app id? Is there a specific build # we should attempt to look at? Are you able to build it locally without issue?

**Comment by omhybrid** [comment]
app id: aae0c4e6

i use windows so locally android build is working good and apk size around 6.0 mb

**Comment by omhybrid** [comment]
@ericb please help

**Comment by ericb** [comment]
@omhybrid Are you using our Package service or building locally?

**Comment by omhybrid** [comment]
Package service

**Comment by omhybrid** [comment]
@ericb  have you any solution?

**Comment by piotrowski** [comment]
@omhybrid You are building for iOS?
What command are you using to build via Ionic Package?
Did you solve the problem in the meantime?

**Comment by omhybrid** [comment]
i build locally using mac.

**Comment by piotrowski** [comment]
Ok, so the problem is solved and this can be closed then?

**Comment by omhybrid** [comment]
yes
