### ISSUE TITLE
Dev Push

### ISSUE THREAD

**Issue by dwieeb** [driftyco/ionic-cloud#8]
@sagivf says in https://github.com/driftyco/ionic-cloud-angular/issues/2:

> Digging trough the code It looks like dev_push has been removed,
> https://github.com/driftyco/ionic-cloud/commit/8906ae31d1c604e0202eb12211737fcc25a786cf
> 
> I'm assuming I am seeing this because i am using the bleeding edge? am I correct? If this effects other users I would strongly recommend updating the docs.
> 
> I also have to mention I liked the dev_push feature. Although it does add some complication and is error prone, I think it fits nicely with Ionics philosophy of embracing the web.
> It allows you to check your code/app while still in the browser which is I big plus despite the disadvantages.
> 
>  I think the problem was more to do with the terminology "limited_push", should have been something along the lines of "Browser Push"  and with the no need to switch a configuration (would have been better for the framework to decided by it's self if it's running in the browser.)
> 
> Happy to hear your thoughts :)

**Comment by dwieeb** [comment]
Yes, `master` branch in this repo is the bleeding edge for the client. There are more changes, too. Have a look at the [Migration Guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide).

Anyway, I agree. You took the words "Browser Push" out of my mouth. That is something we're going to consider for sure, but instead of offering a "development" push option, we'd offer the browser as just another platform to support, just like iOS or Android. This would involve a bit of work to implement on our end, and we're just not ready yet to start that. The demand for such a thing has not been that high.

In its current form, dev push confuses people and the work people do to set it up doesn't fully transfer to getting their app ready to receive native push notifications. That's why we decided to remove it.

As for our docs, we'll be releasing some new documentation for all of this shortly. This is still in development, and we're not ready to fully switch people over to using the new Cloud Client. If you'd like to test out the new code, you can [leave your feedback here](https://github.com/driftyco/ionic-cloud/issues/3). :grin:

**Comment by sagivf** [comment]
Thanks @dwieeb makes perfect sense, hope to see it soon 👍
