### ISSUE TITLE
ionic package - target-device being ignored

### ISSUE THREAD

**Issue by ascotford** [driftyco/ionic-cloud#85]
Reading the cordova docs I should be able to use the following in the config.xml:

<preference name="target-device" value="tablet"/>

The same code works fine using phonegap build but would prefer to use your tools

**Comment by ericb** [comment]
I think you may have meant to paste a config.xml snippet.

**Comment by ascotford** [comment]
Sorry:

<preference name="target-device" value="tablet"/>

**Comment by ascotford** [comment]
`<preference name="target-device" value="tablet"/>`
