### ISSUE TITLE
User Password reset issues

### ISSUE THREAD

**Issue by dwieeb** [driftyco/ionic-cloud#9]
@sagivf says in https://github.com/driftyco/ionic-cloud-angular/issues/3:

> In order to use `user.resetPassword` you need to have a loaded user.
> To have a loaded user you need to log him in which beats the purpose.
> 
> I thought `User.load('user-id’)` would do the trick, 
> but -
> 1) This also beats the point as you don't have the user-id if your not logged in.
> 2) Tried hard coding it and `User.load('user-id’)` doesn't work, I get a 401 (missing token). (Perhaps this deserves it's own issue).
> 
> What am I missing? Is "reset password" different then "forgot password"?
> If so what use case is it good for? Is there a plan to add "forgot password" functionality?

**Comment by dwieeb** [comment]
This method got shuffled around during my refactoring and is currently broken, yes. I didn't pay it any attention because we're actually going to be changing the password reset flow.

I think you're going to like the changes that are coming. We're waiting on some backend service changes but should have the new methods in the client before the full release of this new version.

@devnetics may be able to provide some details.

**Comment by sagivf** [comment]
@dwieeb Thanks for all you help.
@devnetics I know that this is a tough question, but is there any estimate on when things will settle, this issue isn't the most crucial issue but I have opened a couple of others that are - 
https://github.com/driftyco/ionic-cloud/issues/11
https://github.com/driftyco/ionic-cloud/issues/10
? Are we talking weeks or months?

Thanks again for been so responsive.

**Comment by devnetics** [comment]
@sagivf I think we will have the new reset password flows live within a couple of weeks at most. 

You will be able to allow your users to submit a password reset request (with their email), and receive a link to change it. This will update the user credentials for that particular user for your specific app_id. 

I'll try to post more details soon, this is currently being worked on.

**Comment by sagivf** [comment]
Thanks @devnetics for the update. Sounds perfect 👍

**Comment by cklanac** [comment]
I banged my head against the wall for a couple hours yesterday trying to figure this out. I'm going to go take some Advil 💊  for the headache and look forward to the update 👍

**Comment by sagivf** [comment]
@cklanac Can you do me a bug favour and let me know if you are also having this issue - https://github.com/driftyco/ionic-cloud/issues/10. Would help me out a lot...

**Comment by dwieeb** [comment]
@cklanac Sorry about the headache. 😣 This is why I completely removed the method in the latest release. Next week I hope to work with @devnetics to release the password reset overhaul. It's gonna be awesome!

**Comment by dwieeb** [comment]
@cklanac @sagivf We have a new password reset system out there. We're still fine-tuning and styling, but this is essentially complete. I'm going to close this. Our new docs will have the full usage.

**Comment by sagivf** [comment]
Thanks @dwieeb any way to start trying e this out or should we wait for the docs? Are they available?

**Comment by dwieeb** [comment]
@sagivf There are two password reset "flows" now. You can either use our password reset forms (on a website) or you can build your own forms in your app. 

For the former, you'll want to use `auth.passwordResetUrl` to direct the user to the forms -> https://github.com/driftyco/ionic-cloud/blob/069721620027bb5dbf1b60b2644754684cf7af3c/src/auth.ts#L166-L168

For the latter, you'll need to build your own forms.

- The first part of the form should take an email address and then call `auth.requestPasswordReset(email)` -> https://github.com/driftyco/ionic-cloud/blob/069721620027bb5dbf1b60b2644754684cf7af3c/src/auth.ts#L271-L284
- The email address is sent an email with a password reset code
- The second part of the form should take that code as well as a new password and call `auth.confirmPasswordReset(code, newPassword)` -> https://github.com/driftyco/ionic-cloud/blob/069721620027bb5dbf1b60b2644754684cf7af3c/src/auth.ts#L286-L298

**Comment by sagivf** [comment]
@dwieeb I tried installing from master but with all the cross dependencies I'm not sure this is possible. I'll wait for the next release. 

Perhaps we should close this after the release, makes it easier to follow what needs following up.

**Comment by dwieeb** [comment]
@sagivf Why install from master? The latest code (0.8.0-beta.15) is deployed on npm. I had forgotten to push to Github for my work last Friday, but you should be able to use this with what's on npm.

**Comment by sagivf** [comment]
@dwieeb Looking at the code I have it doesn't seem to match the api your mention.

![image](https://cloud.githubusercontent.com/assets/1857466/17863290/c2da278a-68a1-11e6-87c3-3a5246960c45.png)


![image](https://cloud.githubusercontent.com/assets/1857466/17863307/cec13624-68a1-11e6-8c68-7e257f11a968.png)
