### ISSUE TITLE
Apple unclear Push entitlement warning

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#95]
I don't understand what exactly what they mean, but thought It might be something on the Ionic side. Push notification work, but wondering what this is.

![image](https://cloud.githubusercontent.com/assets/1857466/20309740/cfe942ec-ab51-11e6-8003-c3fd10dae29f.png)

**Comment by Fuiste** [comment]
Hey @sagivf, this is related to a change Apple made in versions of Xcode 8 and higher.  You now need to manually activate or deactivate the push notification entitlement once you've added your provisioning profile.

We've updated the docs to reflect this [here](http://docs.ionic.io/services/profiles/#ios-push-certificate), simply find the section marked **Note for users of Xcode 8 and higher**.

**Comment by sagivf** [comment]
Thanks @Fuiste. I actually do have that enabled...
One odd thing I do see it that I've got a file called 'mobile.entitelment' (mobile is the project name) and it has a value of development.

I thought I'd change it but I'm afraid things will stop working.
xxxx hate apple!!! why, why do they have to make everything so complicated for developers.

![image](https://cloud.githubusercontent.com/assets/1857466/20529033/46064dbe-b0d7-11e6-8ee5-668126164006.png)
