### ISSUE TITLE
Ionic.io Dashboard Auth - only shows one page of users

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud#98]

**Comment by sagivf** [comment]
@dwieeb @ericb what's going on? I'm sorry, but It's getting harder and harder to rely on this system when issues are being addressed...

**Comment by ericb** [comment]
Hey @sagivf, sorry for the delay here, I don't think it sent out a notification until you pinged us by name. We'll get this fixed up today.

**Comment by sagivf** [comment]
thank you @ericb. Also there is this one https://github.com/driftyco/ionic-cloud/issues/83#issuecomment-260354112 which seems to be of interest to a few. It's ok if some things take there time, but please try to let us know what is the status on issues that are crucial. Thanks again on advance.

**Comment by ericb** [comment]
Definitely. Thank you! I'll have that deploy issue looked into as well.

**Comment by ericb** [comment]
@sagivf This should be all fixed up now. Let me know if you're still only seeing a single page. 👍
